import {useEffect,useRef,useState} from 'react';
import type {Session} from '@supabase/supabase-js';
import {rpc,supabase,message,type Admin} from './backend';
import {Brand,Bilu,Card,Empty,Notice,Icon} from './ui';
import {useAction,useData} from './hooks';
import {LaunchInterest} from './launch';
import {Reports,Requests} from './queues';
import {Places,Partners,StaffScreen,JournalScreen} from './catalog';
import {Operations,Finance,People,Suggestions} from './operations';
import {AdminSecurityGate} from './security';
import {AdminTutorial} from './tutorial';
import {useSecureAccess} from '../../shared/use-secure-access';
import {securitySessionKey} from '../../shared/security-mfa';
import {privacyAdminAllowed} from '../../shared/privacy';
import {AdminLegalCenter,AdminPrivacyQueue} from './privacy';
type Tab = 'home'|'requests'|'reports'|'places'|'partners'|'operations'|'finance'|'plus'|'suggestions'|'people'|'staff'|'journal'|'privacy'|'launch';
const tabs:Array<{key:Tab;label:string;permission?:string;icon:string}>=[
 {key:'home',label:'Acasă',icon:'⌂'},{key:'requests',label:'Cereri Business',permission:'partners',icon:'▣'},
 {key:'reports',label:'Semnalări',permission:'reports.read',icon:'◇'},{key:'places',label:'Locuri',permission:'staff.read',icon:'⌖'},
 {key:'partners',label:'Parteneri',permission:'partners.read',icon:'▤'},{key:'operations',label:'Sosiri',permission:'operations.read',icon:'↗'},
 {key:'finance',label:'Bani',permission:'money.read',icon:'◎'},{key:'plus',label:'Plus',permission:'plus.manage',icon:'✦'},
 {key:'suggestions',label:'Sugestii',permission:'suggestions.read',icon:'✧'},{key:'people',label:'Oameni',permission:'users.read',icon:'◉'},
 {key:'staff',label:'Echipa',permission:'staff.read',icon:'◌'},{key:'journal',label:'Jurnal',permission:'audit.read',icon:'≡'},{key:'launch',label:'Lansare CeFaci',icon:'✦'},{key:'privacy',label:'Date personale',icon:'◇'}
];
export function App(){return <><ProtectedApp/><AdminLegalCenter/></>;}
function ProtectedApp(){
 const [session,setSession]=useState<Session|null>(null),[ready,setReady]=useState(false),[admin,setAdmin]=useState<Admin|null>(null),[error,setError]=useState(''),[checking,setChecking]=useState(false),[revision,setRevision]=useState(0);
 const [theme,setTheme]=useState(()=>localStorage.getItem('cefaci-admin-theme')==='graphite'?'graphite':'day');
 const sequence=useRef(0);
 const security=useSecureAccess(session?.user.id??'', 'admin', rpc, session ? securitySessionKey(session) : '');
 const logout=async()=>{security.lock();setAdmin(null);try{await rpc('secure_session_close',{p_scope:'admin'});}finally{const {error}=await supabase.auth.signOut({scope:'local'});if(error)throw error;}};
 useEffect(()=>{if(!security.active)return;const activity=()=>security.activity();const focus=()=>void security.check();window.addEventListener('pointerdown',activity);window.addEventListener('keydown',activity);window.addEventListener('focus',focus);return()=>{window.removeEventListener('pointerdown',activity);window.removeEventListener('keydown',activity);window.removeEventListener('focus',focus);};},[security.active,security.activity,security.check]);
 useEffect(()=>{let alive=true;const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,s)=>{if(!alive)return;setSession(previous=>{if(previous?.user.id!==s?.user.id){sequence.current++;setAdmin(null);setError('');}return s;});setReady(true);});supabase.auth.getSession().then(({data,error})=>{if(!alive)return;if(error)setError(error.message);setSession(data.session);setReady(true);});return()=>{alive=false;subscription.unsubscribe();sequence.current++;};},[]);
 useEffect(()=>{if(!session||!security.active){setAdmin(null);setChecking(false);return;}const abort=new AbortController();const current=++sequence.current;setChecking(true);rpc<Admin>('admin_me',{},abort.signal).then(a=>{if(sequence.current===current&&!abort.signal.aborted){setAdmin(a);setError('');}}).catch(e=>{if(sequence.current===current&&!abort.signal.aborted){setAdmin(null);setError(message(e));}}).finally(()=>{if(sequence.current===current&&!abort.signal.aborted)setChecking(false);});return()=>abort.abort();},[session?.user.id,security.active,security.identity?.admin_role,revision]);
 useEffect(()=>{if(!session)return;const timer=setInterval(()=>setRevision(v=>v+1),45000);const focus=()=>setRevision(v=>v+1);window.addEventListener('focus',focus);return()=>{clearInterval(timer);window.removeEventListener('focus',focus);};},[session?.user.id]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('cefaci-admin-theme',theme);},[theme]);
 const toggle=()=>setTheme(t=>t==='day'?'graphite':'day');
 if(!ready)return <div className="auth"><Brand/><p role="status">Se verifică sesiunea…</p></div>;
 if(!session)return <Login/>;
 if(security.error||!security.identity)return <div className="auth"><Card><Brand/><Bilu/><h1>Verificăm accesul…</h1><Notice error={security.error}/><button onClick={()=>void security.check()}>Verifică din nou</button><button onClick={()=>void logout().catch(e=>setError(message(e)))}>Ieși din cont</button><Notice error={error}/></Card></div>;
 if(security.identity.admin_role&&!security.active)return <AdminSecurityGate session={session} forcedChallenge={security.forcedChallenge} onVerified={security.verified} onLogout={logout}/>;
 if(!admin?.role||admin.role!==security.identity.admin_role)return <div className="auth"><Card><Brand/><Bilu/><h1>{security.identity.admin_role?(error?'Accesul nu a putut fi verificat.':'Verificăm accesul…'):'Acest cont nu are acces la Admin.'}</h1><p className="muted">Accesul este acordat de echipa CeFaci. Contul de Client sau Business nu oferă automat un rol aici.</p><Notice error={error}/><div className="actions"><button onClick={()=>setRevision(v=>v+1)} disabled={checking}>Verifică din nou</button><button onClick={()=>void logout().catch(e=>setError(message(e)))}>Ieși din cont</button></div></Card></div>;
 return <Dashboard key={admin.user_id+":"+admin.role} admin={admin} toggle={toggle} theme={theme} onLogout={logout} refreshAccess={()=>setRevision(v=>v+1)}/>;
}
function Login(){
 const [email,setEmail]=useState(''),[sent,setSent]=useState(false),[code,setCode]=useState('');const a=useAction();
 return <div className="auth"><Card><Brand/><Bilu/><p className="eyebrow">Echipa CeFaci</p><h1>Un singur loc.<br/>Toată imaginea.</h1><p className="muted">Cereri, localuri și oamenii care au nevoie de ajutor. Intră cu contul CeFaci al echipei.</p><form onSubmit={e=>{e.preventDefault();void a.run(async()=>{const {error}=sent?await supabase.auth.verifyOtp({email:email.trim().toLowerCase(),token:code.trim(),type:'email'}):await supabase.auth.signInWithOtp({email:email.trim().toLowerCase(),options:{shouldCreateUser:false}});if(error)throw error;if(!sent)setSent(true);},sent?'Cont verificat.':'Verifică emailul contului.');}}><label>Emailul contului CeFaci<input type="email" autoComplete="email" required maxLength={254} value={email} disabled={a.busy||sent} onChange={e=>setEmail(e.target.value)}/></label>{sent&&<label>Codul primit pe email<input inputMode="numeric" autoComplete="one-time-code" required maxLength={16} minLength={6} value={code} onChange={e=>setCode(e.target.value)}/></label>}<Notice error={a.error} success={a.success}/><button className="primary" disabled={a.busy}>{a.busy?'Se verifică…':sent?'Intră în Admin':'Trimite codul'}</button>{sent&&<button type="button" onClick={()=>{setSent(false);setCode('');}}>Schimbă emailul</button>}</form><p className="muted">Doar conturile cu rol activ în echipa CeFaci pot continua.</p></Card></div>;
}
function Dashboard({admin,toggle,theme,refreshAccess,onLogout}:{admin:Admin;toggle:()=>void;theme:string;refreshAccess:()=>void;onLogout:()=>Promise<void>}){
 const [tab,setTab]=useState<Tab>('home'),[refresh,setRefresh]=useState(0),[logoutError,setLogoutError]=useState('');
 const [tourReplay,setTourReplay]=useState(0);
 const visible=tabs.filter(t=>(!['privacy','launch'].includes(t.key)||privacyAdminAllowed(admin.role))&&(!t.permission||admin.permissions.includes(t.permission)));const current=visible.find(t=>t.key===tab)?.key??'home';const title=tabs.find(t=>t.key===current)!.label;
 const reload=()=>{setRefresh(v=>v+1);refreshAccess();};
 return <div className="shell"><aside><Brand/><p className="side-caption">Echipa CeFaci</p><nav aria-label="Meniu Admin">{visible.map(t=><button key={t.key} data-tour-tab={t.key} className={'nav '+(current===t.key?'on':'')} aria-current={current===t.key?'page':undefined} onClick={()=>setTab(t.key)}><Icon name={t.key}/>{t.label}</button>)}</nav><div className="side-note">Răspunsurile și deciziile ajung în conturile Client și Business. Fiecare schimbare rămâne în istoric.</div><div className="identity"><span className="avatar">{(admin.username||'CF').slice(0,2).toUpperCase()}</span><span><strong>@{admin.username||'echipa'}</strong><small>{admin.role}</small></span><button aria-label={theme==='day'?'Mod întunecat':'Mod luminos'} onClick={toggle}><Icon name={theme==='day'?'moon':'sun'}/></button></div><button onClick={()=>setTourReplay(v=>v+1)}>Tur cu Bilu</button><button className="logout" onClick={()=>{sequenceLogout();}}>Ieși din cont</button><Notice error={logoutError}/></aside><main><header className="page-header"><div><p className="eyebrow">{new Date().toLocaleDateString('ro-RO',{timeZone:'Europe/Bucharest',weekday:'long',day:'numeric',month:'long'})}</p><h1>{current==='home'?'Bună, echipa CeFaci.':title}</h1></div><button onClick={reload} aria-label="Actualizează datele"><Icon name="refresh"/> <span>Actualizează</span></button></header><div key={current} className="screen">{current==='launch'?<LaunchInterest admin={admin} refresh={refresh}/>:current==='privacy'?<AdminPrivacyQueue admin={admin} refresh={refresh}/>:current==='home'?<Home admin={admin} refresh={refresh} go={setTab}/>:current==='reports'?<Reports admin={admin} refresh={refresh}/>:current==='requests'?<Requests admin={admin} refresh={refresh}/>:current==='places'?<Places admin={admin} refresh={refresh}/>:current==='partners'?<Partners admin={admin} refresh={refresh}/>:current==='staff'?<StaffScreen admin={admin} refresh={refresh}/>:current==='journal'?<JournalScreen refresh={refresh}/>:current==='operations'?<Operations admin={admin} refresh={refresh}/>:current==='finance'?<Finance refresh={refresh}/>:current==='suggestions'?<Suggestions refresh={refresh}/>:<People admin={admin} plus={current==='plus'}/>}</div><footer>CeFaci · Client + Business + Admin · Datele sunt verificate de server.</footer></main><AdminTutorial userId={admin.user_id} role={admin.role??''} permissions={admin.permissions} availableTabs={visible.map(t=>t.key)} replayToken={tourReplay} onNavigate={setTab}/></div>;
 async function sequenceLogout(){try{await onLogout();}catch(e){setLogoutError(message(e));}}
}
function Home({admin,refresh,go}:{admin:Admin;refresh:number;go:(t:Tab)=>void}){
 const s=useData<Record<string,number|null>>('admin_dashboard',{},refresh);const counts=s.data;
 const cards:[string,string,Tab,string][]=[['support_new','Probleme noi','reports','reports.read'],['missing_place_new','Localuri lipsă','reports','reports.read'],['partner_pending','Cereri Business','requests','partners'],['places','Locuri în catalog','places','staff.read']];
 return <><Notice error={s.error}/>{s.loading&&<p role="status">Se încarcă tabloul de bord…</p>}<div className="kpis">{cards.filter(c=>admin.permissions.includes(c[3])).map(([k,label,t])=><button className="card kpi" key={k} onClick={()=>go(t)}><span className="muted">{label}</span><strong>{counts?.[k]??'—'}</strong><span className="muted">Deschide lista →</span></button>)}</div><div className="home-grid"><Card><h2>De rezolvat</h2>{cards.filter(c=>admin.permissions.includes(c[3])&&c[0]!=='places').map(([k,label,t])=><button className="todo" key={k} onClick={()=>go(t)}><span>{label}</span><strong>{counts?.[k]??'—'}</strong><span>→</span></button>)}{admin.permissions.includes('reports.read')&&<p className="muted">{counts?.support_in_progress??'—'} probleme în lucru · {counts?.legacy_new??'—'} semnalări din versiunile anterioare.</p>}{admin.permissions.includes('operations.read')&&<HomeOperations refresh={refresh} go={()=>go('operations')}/>}</Card><Card><Bilu/><h2>Un răspuns care ajută.</h2><p className="muted">Vezi contextul, verifică dovada și spune clar ce urmează. Solicitantul își găsește răspunsul în aplicație.</p><p className="notice">Deciziile de verificare nu activează automat un parteneriat sau dreptul de proprietar.</p></Card></div>{!cards.some(c=>admin.permissions.includes(c[3]))&&<Empty>Folosește meniul pentru zonele permise rolului tău.</Empty>}</>;
}
function HomeOperations({refresh,go}:{refresh:number;go:()=>void}){const s=useData<Record<string,number>>('admin_operations_summary',{},refresh);return <><Notice error={s.error}/>{s.data&&<>{[['counts_disputed','Numere contestate'],['benefits_pending','Plângeri Plus'],['unclosed','Seri neînchise'],['reservations_pending','Rezervări în așteptare']].map(([key,label])=><button key={key} className="todo" onClick={go}><span>{label}</span><strong>{s.data?.[key]??'—'}</strong><span>→</span></button>)}</>}</>;}
