import {useState} from 'react';
import {KINDS,CAT_LABEL,ZONES} from '../../src/engine/catalog';
import {rpc,type Admin,type Place,type Partner,type Staff,type Journal} from './backend';
import {useAction,useData} from './hooks';
import {Card,Empty,Loading,Notice,Tag,date,money,statusLabel} from './ui';
import {Pagination} from './queues';
export function Places({admin,refresh}:{admin:Admin;refresh:number}){
 const [q,setQ]=useState(''),[selected,setSelected]=useState(''),[page,setPage]=useState(0),[local,setLocal]=useState(0),[added,setAdded]=useState('');const s=useData<Place[]>('admin_places',{p_query:q,p_limit:50,p_offset:page*50},refresh+local);const place=s.data?.find(p=>p.id===selected);const can=admin.permissions.includes('places.edit');
 return <><div className="filters"><label className="grow">Caută un loc<input aria-label="Caută un local" value={q} onChange={e=>{setQ(e.target.value);setPage(0);setSelected('');}} maxLength={100} placeholder="Nume, adresă sau ID"/></label>{can&&<button className="primary" onClick={()=>setSelected('new')}>Adaugă un loc</button>}</div>{added&&<p className="notice positive" role="status">Local adăugat: <strong>{added}</strong>. Poți folosi ID-ul pentru legarea unei cereri Business.</p>}<Loading {...s}/><div className="split"><div className="list">{s.data?.map(p=><button key={p.id} className={'request '+(selected===p.id?'selected':'')} aria-label={'Editează localul: '+p.name} onClick={()=>setSelected(p.id)}><div className="row"><h3>{p.name}</h3><Tag tone={p.status==='on'?'green':'coral'}>{statusLabel[p.status]}</Tag></div><p className="muted">{String(p.edit?.city||p.data?.city||'')} · {p.id}</p></button>)}{s.data?.length===0&&<Empty>Niciun loc găsit.</Empty>}<Pagination page={page} length={s.data?.length||0} setPage={p=>{setPage(p);setSelected('');}}/></div>{selected==='new'&&can?<PlaceEdit key="new" admin={admin} done={id=>{if(id)setAdded(id);setSelected('');setLocal(v=>v+1);}}/>:place?<PlaceEdit key={place.id+':'+place.edited_at} place={place} admin={admin} done={()=>{setSelected('');setLocal(v=>v+1);}}/>:<Card><h2>Catalogul CeFaci</h2><p className="muted">Schimbările se sincronizează în Client și Business. Verifică poziția și informațiile înainte de publicare.</p></Card>}</div></>;
}
function PlaceEdit({place:p,admin,done}:{place?:Place;admin:Admin;done:(id?:string)=>void}){
 const merged={...p?.data,...p?.edit};const initial={name:String(merged.name||p?.name||''),k:String(merged.k||'restaurant'),lat:String(merged.lat??p?.lat??''),lon:String(merged.lon??p?.lon??''),street:String(merged.street||''),city:String(merged.city||''),phone:String(merged.phone||''),website:String(merged.website||''),story:String(merged.story||'')};
 const [form,setForm]=useState(initial),[note,setNote]=useState(''),[history,setHistory]=useState(false);const a=useAction();const can=admin.permissions.includes('places.edit');
 const field=(key:keyof typeof initial,label:string,type='text')=><label>{label}<input type={type} value={form[key]} disabled={!can||a.busy} required={['name','lat','lon'].includes(key)} maxLength={key==='name'?160:500} step={type==='number'?'any':undefined} min={key==='lat'?'-90':key==='lon'?'-180':undefined} max={key==='lat'?'90':key==='lon'?'180':undefined} onChange={e=>setForm(f=>({...f,[key]:e.target.value}))}/></label>;
 const save=async()=>{const k=KINDS[form.k];if(!k)throw new Error('Alege un fel de loc valid.');const lat=Number(form.lat),lon=Number(form.lon);if(!form.name.trim()||!form.lat.trim()||!form.lon.trim()||!Number.isFinite(lat)||!Number.isFinite(lon)||Math.abs(lat)>90||Math.abs(lon)>180)throw new Error('Verifică numele și coordonatele.');if(form.website&&!/^https?:\/\//i.test(form.website))throw new Error('Site-ul trebuie să înceapă cu https:// sau http://.');const values:Record<string,unknown>={...form,name:form.name.trim(),lat,lon};if(!p||form.k!==initial.k){values.cat=k.cat;values.kind=k.label;}if(p){const edits:Record<string,unknown>={};for(const [key,value] of Object.entries(values))if(String(value)!==String((initial as Record<string,string>)[key]??merged[key]??''))edits[key]=value;await rpc('admin_place_save',{p_id:p.id,p_edit:edits,p_note:note.trim()});done();}else{const id=await rpc<string>('admin_place_add',{p_data:{...values,price:k.price,vibes:k.vibes,cuisines:[],zone:[...ZONES].sort((a,b)=>(a.lat-lat)**2+(a.lon-lon)**2-((b.lat-lat)**2+(b.lon-lon)**2))[0]?.id},p_note:note.trim()});done(id);}};
 return <Card className="detail"><h2>{p?p.name:'Un loc nou'}</h2>{p&&<div className="row"><Tag>{statusLabel[p.status]}</Tag><span className="muted">{p.id}</span></div>}<form onSubmit={e=>{e.preventDefault();void a.run(save);}}>{field('name','Numele localului')}<label>Felul locului<select aria-label="Felul locului" value={form.k} disabled={!can||a.busy} onChange={e=>setForm(f=>({...f,k:e.target.value}))}>{Object.entries(KINDS).map(([key,k])=><option value={key} key={key}>{k.label} · {CAT_LABEL[k.cat]}</option>)}</select></label><div className="form-grid">{field('lat','Latitudine','number')}{field('lon','Longitudine','number')}</div>{field('street','Adresă')}{field('city','Oraș')}<div className="form-grid">{field('phone','Telefon')}{field('website','Site')}</div><label>Descriere<textarea aria-label="Descriere" value={form.story} disabled={!can||a.busy} maxLength={2000} rows={4} onChange={e=>setForm(f=>({...f,story:e.target.value}))}/></label>{(can||admin.permissions.includes('places.hide'))&&<label>Motivul modificării<input required minLength={5} maxLength={300} value={note} onChange={e=>setNote(e.target.value)}/></label>}<Notice error={a.error} success={a.success}/><div className="actions">{can&&<button className="primary" disabled={a.busy||note.trim().length<5}>{p?'Salvează localul':'Publică localul'}</button>}{p&&admin.permissions.includes('places.hide')&&p.status!=='gone'&&<button type="button" disabled={a.busy||note.trim().length<5} onClick={()=>void a.run(async()=>{await rpc('admin_place_status',{p_id:p.id,p_hidden:p.status==='on',p_note:note.trim()});done();})}>{p.status==='on'?'Ascunde localul':'Arată localul'}</button>}</div></form>{p&&(can||admin.permissions.includes('places.hide')||admin.permissions.includes('partners'))&&<><button onClick={()=>setHistory(!history)}>{history?'Închide istoricul':'Vezi istoricul localului'}</button>{history&&<PlaceHistory id={p.id}/>}</>}</Card>;
}
function PlaceHistory({id}:{id:string}){const s=useData<Array<{id:number;action:string;at:string;note:string}>>('admin_place_log',{p_venue:id});return <><Loading {...s}/>{s.data?.length===0&&<p className="muted">Nicio modificare înregistrată.</p>}{s.data?.map(x=><div className="log" key={x.id}><strong>{x.action}</strong><p className="muted">{date(x.at)}</p><p>{x.note||'—'}</p></div>)}</>;}
export function Partners({admin,refresh}:{admin:Admin;refresh:number}){
 const [q,setQ]=useState('');const s=useData<Partner[]>('admin_partners',{},refresh);const filtered=s.data?.filter(p=>(p.name+' '+p.firm+' '+p.cui).toLowerCase().includes(q.toLowerCase()));
 return <><p className="lead">Parteneriatele existente, echipa și condițiile lor. Tarifele se aplică per persoană eligibilă, cel mult zece pe vizită.</p><label>Caută un partener<input value={q} onChange={e=>setQ(e.target.value)} maxLength={100}/></label><Loading {...s}/><div className="partner-grid">{filtered?.map(p=><Card key={p.venue_id}><div className="row"><h2>{p.name}</h2><Tag tone="green">{statusLabel[p.status]}</Tag></div>{p.founder&&<Tag tone="yellow">Fondator</Tag>}<dl><dt>Firmă</dt><dd>{p.firm}</dd><dt>CUI</dt><dd>{p.cui}</dd><dt>Treapta contractuală</dt><dd>{p.price_tier||'Neconfigurată'}</dd><dt>Activat</dt><dd>{p.activated_at}</dd><dt>Gratuitate până la</dt><dd>{p.free_until}</dd></dl>{p.price_tier&&<p className="muted">Rezervare {Math.max(0,[0,2,5,8][p.price_tier]-(p.founder?1:0))} lei/pers. · Drop {Math.max(0,[0,3,7,10][p.price_tier]-(p.founder?1:0))} lei/pers.</p>}<h3>Echipa localului</h3>{p.team?.map(m=><p key={m.username} className="muted">@{m.username} · {m.role}</p>)}{!p.team?.length&&<p className="muted">Niciun membru activ.</p>}<p className="muted">{p.flags} diferențe de bon · {p.noshow} neveniri · {p.unclosed} seri neînchise.</p>{p.month&&<p>Comisionul perioadei: {money(p.month.fee)}</p>}</Card>)}</div>{filtered?.length===0&&<Empty>Niciun partener găsit. Verificarea unei cereri Business nu creează automat un parteneriat.</Empty>}<Card><h2>Contracte și circuit fiscal</h2><p className="muted">Activarea unui partener, schimbarea firmei sau a treptei cere contractul real și verificarea condițiilor. Semnarea contractelor și emiterea facturilor nu sunt configurate.</p><Tag tone="yellow">Facturare oprită</Tag></Card></>;
}
export function StaffScreen({admin,refresh}:{admin:Admin;refresh:number}){
 const [local,setLocal]=useState(0),[selected,setSelected]=useState<Staff|null>(null);const s=useData<Staff[]>('admin_staff_list',{},refresh+local);const manage=admin.permissions.includes('staff.manage');
 return <><Loading {...s}/><div className="split"><Card><h2>Echipa CeFaci</h2>{s.data?.map(p=><div className="staff-row" key={p.user_id}><span><strong>@{p.username}</strong><small>{p.role}</small></span>{manage&&p.user_id!==admin.user_id&&<button aria-label={'Schimbă rolul: '+p.username} onClick={()=>setSelected(p)}>Gestionează</button>}{p.user_id===admin.user_id&&<Tag>Tu</Tag>}</div>)}</Card>{manage?<StaffEdit key={selected?.user_id||'new'} target={selected} admin={admin} done={()=>{setSelected(null);setLocal(v=>v+1);}}/>:<Card><h2>Acces după rol</h2><p className="muted">Fondatorul și Adminul gestionează echipa. Permisiunile sunt verificate de server la fiecare operațiune.</p></Card>}</div></>;
}
function StaffEdit({target,admin,done}:{target:Staff|null;admin:Admin;done:()=>void}){
 const [q,setQ]=useState(''),[matches,setMatches]=useState<Array<{user_id:string;username:string}>>([]),[picked,setPicked]=useState<{user_id:string;username:string}|null>(target),[role,setRole]=useState(target?.role||'suport'),[note,setNote]=useState('');const a=useAction();const roles=admin.role==='fondator'?['fondator','admin','editor','moderator','suport','contabil']:['editor','moderator','suport'];
 const change=async(remove=false)=>{if(!picked)throw new Error('Alege un cont.');await rpc('admin_staff_change',{p_user:picked.user_id,p_role:remove?null:role,p_note:note.trim(),p_expected_role:target?.role||null});done();};
 return <Card><h2>{target?'Gestionează @'+target.username:'Adaugă în echipă'}</h2>{!target&&<><form onSubmit={e=>{e.preventDefault();void a.run(async()=>{const list=await rpc<Array<{user_id:string;username:string}>>('admin_staff_search',{p_query:q.trim()});setMatches(list);},'Căutare finalizată.');}}><label>Username exact<input value={q} onChange={e=>{setQ(e.target.value);setPicked(null);setMatches([]);}} required minLength={3} maxLength={30} placeholder="@username"/></label><button disabled={a.busy}>Caută contul</button></form>{matches.map(u=><button className="picker-row" key={u.user_id} onClick={()=>setPicked(u)}>Alege @{u.username}</button>)}</>}{picked&&<p className="notice">Cont ales: @{picked.username}</p>}<form onSubmit={e=>{e.preventDefault();void a.run(()=>change());}}><label>Rol în echipa CeFaci<select aria-label="Rol în echipa CeFaci" value={role} onChange={e=>setRole(e.target.value)}>{target&&!roles.includes(target.role)&&<option value={target.role}>{target.role}</option>}{roles.map(r=><option value={r} key={r}>{r}</option>)}</select></label><label>Motivul schimbării<input value={note} onChange={e=>setNote(e.target.value)} minLength={5} maxLength={300} required/></label><Notice error={a.error} success={a.success}/><div className="actions"><button className="primary" disabled={a.busy||!picked||note.trim().length<5}>Salvează rolul</button>{target&&<button type="button" className="destructive" disabled={a.busy||note.trim().length<5} onClick={()=>void a.run(()=>change(true),'Membrul a fost scos din echipă.')}>Scoate din echipă</button>}</div></form><p className="muted">Adminul poate gestiona doar editori, moderatori și suport. Nimeni nu își schimbă propriul rol.</p></Card>;
}
export function JournalScreen({refresh}:{refresh:number}){
 const [page,setPage]=useState(0);const s=useData<Array<Journal&{origin:string;subject_id:string}>>('admin_activity',{p_limit:50,p_offset:page*50},refresh);
 return <><p className="lead">Deciziile, accesările de documente și schimbările de rol rămân în istoric.</p><Loading {...s}/><Card>{s.data?.map(j=><div className="log" key={j.id}><div className="row"><Tag>{j.origin}</Tag><strong>{j.action}</strong><span className="muted">{date(j.at)}</span></div><p>{j.summary||j.note||j.reason||'—'}</p><small className="muted">@{j.username||'cont șters'} · {j.subject_id}</small></div>)}{s.data?.length===0&&<Empty>Jurnalul nu are încă înregistrări.</Empty>}<Pagination page={page} length={s.data?.length||0} setPage={setPage}/></Card></>;
}
