import {useState} from 'react';
import {rpc,type Admin} from './backend';
import {useAction,useData} from './hooks';
import {Card,Empty,Loading,Notice,Tag,date,money} from './ui';
import {Pagination} from './queues';
type Count={version:number;people:number;adults:number;drop_adults:number;state:string;deadline:string;reason:string};
type Benefit={version:number;state:string;reason:string;reply:string;decision_reason:string};
type Visit={id:string;venue_id:string;venue_name:string;work_day:string;created_at:string;kind:string;people:number;outcome:string;closed_at:string|null;proof:string;count:Count|null;benefit:Benefit|null;bill:number|null;discount_amount:number|null;discount_pct:number;discount_scope:string};
type OperationData={visits:Visit[];reservations:Array<{id:string;venue_name:string;at:string;people:number;status:string;reason:string;proposal_expires_at?:string}>;total_visits:number;total_reservations:number};
function today(){return new Date().toLocaleDateString('en-CA',{timeZone:'Europe/Bucharest'});}
function start(){return today().slice(0,8)+'01';}
function Period({from,to,setFrom,setTo,venue,setVenue}:{from:string;to:string;setFrom:(v:string)=>void;setTo:(v:string)=>void;venue:string;setVenue:(v:string)=>void}){return <div className="filters"><label>De la<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Până la<input type="date" value={to} min={from} onChange={e=>setTo(e.target.value)}/></label><label>ID local (opțional)<input value={venue} maxLength={40} onChange={e=>setVenue(e.target.value)} placeholder="Toate localurile"/></label></div>;}
export function Operations({admin,refresh}:{admin:Admin;refresh:number}){
 const [from,setFrom]=useState(start),[to,setTo]=useState(today),[venue,setVenue]=useState(''),[filter,setFilter]=useState('attention'),[page,setPage]=useState(0),[local,setLocal]=useState(0),[selected,setSelected]=useState('');
 const args={p_from:from,p_to:to,p_venue:venue.trim()||null,p_filter:filter,p_limit:50,p_offset:page*50};const s=useData<OperationData>('admin_operations',args,refresh+local);const visit=s.data?.visits.find(v=>v.id===selected);
 const change=(fn:(v:string)=>void)=>(v:string)=>{fn(v);setPage(0);setSelected('');};
 return <><p className="lead">Sosiri, diferențe de număr, reduceri contestate și seri neînchise. Ziua operațională începe la 05:00, Europe/Bucharest.</p><Period from={from} to={to} setFrom={change(setFrom)} setTo={change(setTo)} venue={venue} setVenue={change(setVenue)}/><label>Ce afișăm<select aria-label="Ce afișăm" value={filter} onChange={e=>change(setFilter)(e.target.value)}><option value="attention">De verificat</option><option value="all">Toate sosirile și rezervările</option></select></label><Loading {...s}/>{s.data&&<p className="muted">{s.data.total_visits} sosiri · {s.data.total_reservations} rezervări pentru filtrele alese.</p>}<div className="split"><div className="list">{s.data?.visits.map(v=><button className={'request '+(selected===v.id?'selected':'')} key={v.id} aria-label={'Verifică sosirea: '+v.id} onClick={()=>setSelected(v.id)}><h3>{v.venue_name}</h3><p>{v.people} persoane · {v.kind}</p><div className="row"><Tag>{v.outcome}</Tag>{v.count?.state==='disputed'&&<Tag tone="coral">Număr contestat</Tag>}{v.benefit?.state==='pending'&&<Tag tone="yellow">Plângere Plus</Tag>}{!v.closed_at&&<Tag>Neînchisă</Tag>}</div><p className="muted">{date(v.created_at)}</p></button>)}{s.data?.visits.length===0&&<Empty>Nicio sosire pentru filtrele alese.</Empty>}<Pagination page={page} length={Math.max(s.data?.visits.length||0,s.data?.reservations.length||0)} setPage={p=>{setPage(p);setSelected('');}}/></div>{visit?<VisitDetail key={visit.id+':'+visit.count?.version+':'+visit.benefit?.version} visit={visit} admin={admin} done={()=>{setSelected('');setLocal(v=>v+1);}}/>:<Card><h2>Alege o sosire</h2><p className="muted">Deciziile folosesc numărul și versiunea păstrate de server. Cazurile neclare rămân excluse din totalul final.</p></Card>}</div><Card><h2>Rezervări</h2>{s.data?.reservations.map(r=><div className="log" key={r.id}><div className="row"><strong>{r.venue_name}</strong><Tag>{r.status}</Tag></div><p>{r.people} persoane · {date(r.at)}</p>{r.reason&&<p className="muted preserve">{r.reason}</p>}{r.proposal_expires_at&&<p className="muted">Propunere valabilă până la {date(r.proposal_expires_at)}</p>}</div>)}{s.data?.reservations.length===0&&<p className="muted">Nicio rezervare pentru filtrele alese.</p>}</Card></>;
}
function VisitDetail({visit:v,admin,done}:{visit:Visit;admin:Admin;done:()=>void}){
 const [people,setPeople]=useState(String(v.count?.people??v.people)),[adults,setAdults]=useState(String(v.count?.adults??v.people)),[drop,setDrop]=useState(String(v.count?.drop_adults??0)),[reason,setReason]=useState('');const a=useAction();const can=admin.permissions.includes('operations.decide');
 const numeric=(label:string,value:string,set:(v:string)=>void,max:number)=><label>{label}<input type="number" min={label==='Persoane confirmate'?1:0} max={max} step="1" value={value} onChange={e=>set(e.target.value)} required disabled={!can||a.busy}/></label>;
 return <Card className="detail"><h2>{v.venue_name}</h2><dl><dt>Sosire</dt><dd>{date(v.created_at)}</dd><dt>Zi operațională</dt><dd>{v.work_day}</dd><dt>Sursă</dt><dd>{v.kind}</dd><dt>Dovadă</dt><dd>{v.proof}</dd><dt>Stare</dt><dd>{v.outcome}</dd><dt>Reducere</dt><dd>{v.discount_pct}% · {v.discount_scope}</dd>{v.bill!==null&&<><dt>Încasare după reduceri</dt><dd>{money(v.bill)}</dd></>}</dl>{v.count&&<><h3>Numărul persoanelor</h3><p className="muted">Stare: {v.count.state} · Versiunea {v.count.version} · Termen {date(v.count.deadline)}</p>{v.count.reason&&<p className="preserve">{v.count.reason}</p>}{can&&['awaiting','disputed'].includes(v.count.state)&&<form onSubmit={e=>{e.preventDefault();void a.run(async()=>{await rpc('admin_count_resolve_v2',{p_visit:v.id,p_version:v.count!.version,p_people:Number(people),p_adults:Number(adults),p_drop_adults:Number(drop),p_reason:reason.trim()});done();});}}><div className="form-grid">{numeric('Persoane confirmate',people,setPeople,v.people)}{numeric('Persoane eligibile de minimum 12 ani',adults,setAdults,Number(people))}{numeric('Persoane cu sursă Drop',drop,setDrop,Number(adults))}</div><label>Motivul deciziei<textarea aria-label="Motivul deciziei" value={reason} onChange={e=>setReason(e.target.value)} required minLength={5} maxLength={1000}/></label><button className="primary" disabled={a.busy||reason.trim().length<5}>Confirmă numărul</button></form>}</>}{v.benefit&&<><h3>Plângere privind reducerea</h3><Tag tone="yellow">{v.benefit.state}</Tag><p className="preserve">{v.benefit.reason}</p>{v.benefit.reply&&<p className="notice preserve">Răspunsul localului: {v.benefit.reply}</p>}{v.benefit.decision_reason&&<p className="notice preserve">Decizia: {v.benefit.decision_reason}</p>}{can&&v.benefit.state==='pending'&&<><label>Motivul deciziei privind reducerea<textarea aria-label="Motivul deciziei privind reducerea" value={reason} onChange={e=>setReason(e.target.value)} minLength={5} maxLength={1000}/></label><div className="actions"><button className="primary" disabled={a.busy||reason.trim().length<5} onClick={()=>void a.run(async()=>{await rpc('admin_benefit_decide_v2',{p_visit:v.id,p_version:v.benefit!.version,p_uphold:true,p_reason:reason.trim()});done();})}>Admite plângerea</button><button className="destructive" disabled={a.busy||reason.trim().length<5} onClick={()=>void a.run(async()=>{await rpc('admin_benefit_decide_v2',{p_visit:v.id,p_version:v.benefit!.version,p_uphold:false,p_reason:reason.trim()});done();})}>Respinge plângerea</button></div><p className="muted">Compensarea Plus este aplicată de server conform limitei din ultimele 60 de zile.</p></>}</>}<Notice error={a.error} success={a.success}/></Card>;
}
type Financial={billing_ready:boolean;estimate:boolean;partial:boolean;missing:number;blocked:number;revenue:number;discounts:number;fee:number;remaining:number|null;would_pay:number;visits:number;venues:Array<{venue_id:string;name:string;finance:Financial}>};
export function Finance({refresh}:{refresh:number}){
 const [from,setFrom]=useState(start),[to,setTo]=useState(today),[venue,setVenue]=useState('');const s=useData<Financial>('admin_finance',{p_from:from,p_to:to,p_venue:venue.trim()||null},refresh);const f=s.data;
 return <><Period from={from} to={to} setFrom={setFrom} setTo={setTo} venue={venue} setVenue={setVenue}/><Loading {...s}/>{f&&<><Card className="net"><p className="eyebrow">Rămas localurilor</p><strong>{f.remaining===null?'Total parțial':money(f.remaining)}</strong><p className="muted">Încasări după reduceri − comision CeFaci. Reducerile nu se scad a doua oară.</p></Card><div className="kpis">{[['Încasări după reduceri',f.revenue],['Reduceri acordate',f.discounts],['Comision CeFaci',f.fee],['Informativ în gratuitate',f.would_pay]].map(([label,value])=><Card className="kpi" key={String(label)}><span className="muted">{label}</span><strong>{money(value)}</strong></Card>)}</div>{f.partial&&<p className="notice" role="status">Total parțial: {f.missing} sosiri fără sumă completă și {f.blocked} cazuri în verificare. Suma rămasă nu este un total final.</p>}<Card><h2>Pe local</h2><div className="table-scroll"><table><thead><tr><th>Local</th><th>Încasări</th><th>Comision</th><th>Rămas</th><th>Stare</th></tr></thead><tbody>{f.venues.map(v=><tr key={v.venue_id}><th>{v.name}</th><td>{money(v.finance.revenue)}</td><td>{money(v.finance.fee)}</td><td>{v.finance.remaining===null?'—':money(v.finance.remaining)}</td><td>{v.finance.partial?'Parțial':'Calcul complet'}</td></tr>)}</tbody></table></div>{f.venues.length===0&&<p className="muted">Niciun partener în această perioadă.</p>}</Card><Card><h2>Calcul pentru verificare</h2><Tag tone="yellow">Facturare oprită</Tag><p className="muted">Circuitul fiscal, facturile ANAF, încasarea plăților și extrasele nu sunt configurate. Aceste sume nu reprezintă facturi emise. Zi financiară: Europe/Bucharest, prag 05:00.</p></Card></>}</>;
}
type User={id:string;username:string;first_name:string;created_at:string;staff_role:string|null;plus_until:string|null;no_shows:number;plus_grant_allowed:boolean};
export function People({admin,plus=false}:{admin:Admin;plus?:boolean}){
 const [q,setQ]=useState(''),[user,setUser]=useState<User|null>(null),[searched,setSearched]=useState(false);const a=useAction();
 return <><p className="lead">{plus?'Ajutor punctual și plângeri Plus.':'Caută un cont după username exact, doar pentru cazul pe care îl rezolvi.'}</p><Card><form onSubmit={e=>{e.preventDefault();void a.run(async()=>{const u=await rpc<User|null>('admin_user_lookup',{p_username:q.trim()});setUser(u);setSearched(true);},'Căutare finalizată.');}}><label>Username exact<input value={q} onChange={e=>{setQ(e.target.value);setUser(null);setSearched(false);}} minLength={3} maxLength={21} required placeholder="@username"/></label><button className="primary" disabled={a.busy}>Caută utilizatorul</button><Notice error={a.error}/></form></Card>{searched&&!user&&<Empty>Nu am găsit acest cont.</Empty>}{user&&<Card><h2>@{user.username}</h2><dl><dt>Prenume</dt><dd>{user.first_name||'—'}</dd><dt>Cont creat</dt><dd>{date(user.created_at)}</dd><dt>Plus până la</dt><dd>{date(user.plus_until)}</dd><dt>Neveniri înregistrate</dt><dd>{user.no_shows}</dd>{user.staff_role&&<><dt>Rol în echipă</dt><dd>{user.staff_role}</dd></>}</dl>{admin.permissions.includes('plus.manage')&&user.plus_grant_allowed&&<PlusGrant key={user.id} user={user} updated={until=>setUser({...user,plus_until:until})}/>}</Card>}{plus&&<Card><h2>Plângeri privind reducerea</h2><p className="muted">Cazurile verificate, răspunsul localului și decizia se găsesc în Sosiri, filtrul „De verificat”. Compensarea de șapte zile este legată de o plângere reală și aprobată.</p></Card>}</>;
}
function PlusGrant({user,updated}:{user:User;updated:(u:string)=>void}){
 const [reason,setReason]=useState(''),[key]=useState(()=>crypto.randomUUID()),[sent,setSent]=useState(false),[locked,setLocked]=useState(false);const a=useAction();
 return <form onSubmit={e=>{e.preventDefault();setLocked(true);void a.run(async()=>{const r=await rpc<{plus_until:string}>('admin_plus_grant',{p_user:user.id,p_days:1,p_reason:reason.trim(),p_key:key});updated(r.plus_until);setSent(true);},'O zi Plus a fost acordată.');}}><h3>O zi Plus de suport</h3><p className="muted">Cel mult o acordare pe client în 60 de zile. Fiecare acordare are motiv și rămâne în jurnal.</p><label>Motivul acordării<textarea aria-label="Motivul acordării" required minLength={5} maxLength={1000} rows={3} value={reason} disabled={sent||locked} onChange={e=>setReason(e.target.value)}/></label><Notice error={a.error} success={a.success}/><button className="primary" disabled={a.busy||sent||reason.trim().length<5}>{sent?'Zi Plus acordată':'Acordă o zi Plus'}</button>{locked&&!sent&&a.error&&<p className="muted">Poți reîncerca aceeași cerere fără a acorda ziua de două ori.</p>}</form>;
}
export function Suggestions({refresh}:{refresh:number}){
 const s=useData<Array<{venue_id:string;name:string;visits:number;receipts:number;people:number;last_visit:string}>>('admin_partner_suggestions',{},refresh);const [copied,setCopied]=useState('');const a=useAction();
 return <><p className="lead">Locuri nepartenere cu activitate reală în ultimele 12 luni, din grupuri de cel puțin cinci conturi. Primul contact este în persoană sau la telefon.</p><Loading {...s}/><Notice error={a.error}/><div className="partner-grid">{s.data?.map(v=><Card key={v.venue_id}><h2>{v.name}</h2><dl><dt>Check-in-uri</dt><dd>{v.visits}</dd><dt>Bonuri înregistrate</dt><dd>{v.receipts}</dd><dt>Conturi distincte</dt><dd>{v.people}</dd><dt>Ultima vizită</dt><dd>{date(v.last_visit)}</dd></dl><p className="muted">„Bună! Oamenii aleg {v.name} prin CeFaci. Am înregistrat {v.visits} check-in-uri în ultimul an și vrem să discutăm un parteneriat care să vă aducă rezervări și clienți noi.”</p><button onClick={()=>void a.run(async()=>{await navigator.clipboard.writeText(`Bună! Oamenii aleg ${v.name} prin CeFaci. Am înregistrat ${v.visits} check-in-uri în ultimul an și vrem să discutăm un parteneriat care să vă aducă rezervări și clienți noi.`);setCopied(v.venue_id);},'Text copiat.')}>{copied===v.venue_id?'Text copiat':'Copiază textul pentru local'}</button></Card>)}</div>{s.data?.length===0&&<Empty>Niciun loc cu suficiente date agregate momentan.</Empty>}</>;
}
