import {useState} from 'react';
import {rpc,type Admin,type Report,type PartnerRequest,type Place} from './backend';
import {useAction,useData} from './hooks';
import {Card,Empty,Loading,Notice,Photo,Tag,date,statusLabel} from './ui';
const states=['new','in_progress','resolved','rejected'];
export function Reports({admin,refresh}:{admin:Admin;refresh:number}){
 const [status,setStatus]=useState('new'),[kind,setKind]=useState(''),[source,setSource]=useState(''),[selected,setSelected]=useState(''),[page,setPage]=useState(0),[local,setLocal]=useState(0);
 const s=useData<Report[]>('admin_support_reports',{p_status:status||null,p_kind:kind||null,p_source:source||null,p_limit:50,p_offset:page*50},refresh+local);
 const report=s.data?.find(r=>r.origin+':'+r.id===selected);
 return <><div className="filters"><label>Stare<select aria-label="Stare" value={status} onChange={e=>{setStatus(e.target.value);setPage(0);setSelected('');}}><option value="">Toate</option>{states.map(s=><option key={s} value={s}>{statusLabel[s]}</option>)}</select></label><label>Tip<select aria-label="Tip" value={kind} onChange={e=>{setKind(e.target.value);setPage(0);setSelected('');}}><option value="">Toate</option><option value="issue">Problemă</option><option value="missing_place">Local lipsă</option></select></label><label>Aplicație<select aria-label="Aplicație" value={source} onChange={e=>{setSource(e.target.value);setPage(0);setSelected('');}}><option value="">Toate</option><option value="client">Client</option><option value="business">Business</option></select></label></div><Loading {...s}/><div className="split"><div className="list">{s.data?.map(r=><button className={'request '+(selected===r.origin+':'+r.id?'selected':'')} key={r.origin+':'+r.id} aria-label={'Deschide: '+r.title} onClick={()=>setSelected(r.origin+':'+r.id)}><div className="row"><Tag tone={r.kind==='missing_place'?'yellow':'blue'}>{r.kind==='missing_place'?'Local lipsă':'Problemă'}</Tag><Tag>{r.source==='business'?'Business':'Client'}</Tag></div><h3>{r.title}</h3><p className="muted">@{r.username||'cont șters'} · {date(r.submitted_at||r.created_at)}</p><span className="muted">{statusLabel[r.status]||r.status}</span></button>)}{s.data?.length===0&&<Empty>Nicio semnalare pentru filtrele alese.</Empty>}<Pagination page={page} length={s.data?.length||0} setPage={p=>{setPage(p);setSelected('');}}/></div>{report?<ReportDetail key={report.id+':'+report.version} report={report} admin={admin} onSaved={()=>{setLocal(v=>v+1);setSelected('');}}/>:<Card><h2>Alege o semnalare</h2><p className="muted">Problemele raportate din Profilul Clientului și Ajutorul Business apar aici. Localurile lipsă ajung în aceeași listă.</p></Card>}</div></>;
}
function ReportDetail({report:r,admin,onSaved}:{report:Report;admin:Admin;onSaved:()=>void}){
 const [answer,setAnswer]=useState(r.answer||''),[status,setStatus]=useState(r.status),[photo,setPhoto]=useState(false);const a=useAction();
 const can=admin.permissions.includes(r.origin==='legacy'?'reports.close':'support.manage');
 const options=r.origin==='legacy'?['resolved','rejected']:states;
 return <Card className="detail"><div className="row"><Tag>{r.origin==='legacy'?'Versiune anterioară':r.source==='business'?'Business':'Client'}</Tag><Tag>{statusLabel[r.status]}</Tag></div><h2>{r.title}</h2><p className="preserve">{r.description}</p><dl><dt>Trimis de</dt><dd>@{r.username||'cont șters'}</dd><dt>Local</dt><dd>{r.venue_id||'—'}</dd><dt>Data</dt><dd>{date(r.submitted_at||r.created_at)}</dd></dl>{r.photo_available&&<><button onClick={()=>setPhoto(!photo)}>{photo?'Închide poza':'Vezi poza'}</button>{photo&&<Photo id={r.id}/>}</>}<form onSubmit={e=>{e.preventDefault();void a.run(async()=>{await rpc(r.origin==='legacy'?'admin_legacy_report_update':'admin_support_report_update',{p_id:r.id,p_status:status,p_answer:answer.trim(),p_version:r.version});onSaved();});}}><label>Starea cererii<select aria-label="Starea cererii" value={status} disabled={!can||a.busy} onChange={e=>setStatus(e.target.value)}>{!options.includes(r.status)&&<option value={r.status}>{statusLabel[r.status]}</option>}{options.map(s=><option key={s} value={s}>{statusLabel[s]}</option>)}</select></label><label>Răspuns pentru solicitant<textarea aria-label="Răspuns pentru solicitant" value={answer} disabled={!can||a.busy} maxLength={r.origin==='legacy'?300:2000} rows={5} onChange={e=>setAnswer(e.target.value)} placeholder="Ce ai verificat și care este următorul pas?"/></label><p className="muted">Acest răspuns este vizibil în aplicația solicitantului.</p><Notice error={a.error} success={a.success}/>{can?<button className="primary" disabled={a.busy||status==='new'&&r.origin==='legacy'}>Salvează răspunsul</button>:<p className="muted">Rolul tău permite citirea acestei cereri.</p>}</form></Card>;
}
export function Requests({admin,refresh}:{admin:Admin;refresh:number}){
 const [status,setStatus]=useState('pending'),[selected,setSelected]=useState(''),[local,setLocal]=useState(0);
 const s=useData<PartnerRequest[]>('admin_partner_requests',{p_status:status},refresh+local);const r=s.data?.find(r=>r.id===selected);
 return <><p className="lead">Revendicări, localuri noi și dispute de proprietate. Verificarea dosarului precedă contractul și acordarea accesului.</p><div className="filters"><label>Stare<select aria-label="Stare" value={status} onChange={e=>{setStatus(e.target.value);setSelected('');}}>{['pending','verified','rejected','cancelled'].map(s=><option key={s} value={s}>{statusLabel[s]}</option>)}</select></label></div><Loading {...s}/><div className="split"><div className="list">{s.data?.map(r=><button key={r.id} className={'request '+(r.id===selected?'selected':'')} aria-label={'Deschide cererea: '+(r.venue_name||r.details.venue_name||r.details.firm)} onClick={()=>setSelected(r.id)}><div className="row"><Tag tone={r.kind==='dispute'?'coral':'blue'}>{r.kind==='claim'?'Revendicare':r.kind==='new'?'Local nou':'Dispută'}</Tag><Tag>{statusLabel[r.status]}</Tag></div><h3>{r.venue_name||r.details.venue_name||r.details.firm}</h3><p className="muted">@{r.applicant_username||'cont șters'} · {date(r.submitted_at)}</p></button>)}{s.data?.length===0&&<Empty>Nicio cerere Business în această stare.</Empty>}</div>{r?<RequestDetail key={r.id+':'+r.status} r={r} admin={admin} done={()=>{setLocal(v=>v+1);setSelected('');}}/>:<Card><h2>Alege un dosar</h2><p className="muted">Verifică firma în registrul relevant, documentul și dreptul solicitantului. Pentru un local nou, adaugă întâi locul în catalog, apoi leagă dosarul de el.</p></Card>}</div></>;
}
function RequestDetail({r,admin,done}:{r:PartnerRequest;admin:Admin;done:()=>void}){
 const [proof,setProof]=useState(false),[verified,setVerified]=useState(false),[note,setNote]=useState(''),[target,setTarget]=useState(r.venue_id||'');const a=useAction();
 const labels:Record<string,string>={requester_name:'Nume solicitant',requester_role:'Calitate',firm:'Firmă',cui:'CUI',phone:'Telefon',venue_name:'Local nou',address:'Adresă',city:'Oraș',category:'Categorie'};
 const may=admin.permissions.includes('partners')&&r.status==='pending';
 async function decide(decision:string){await rpc('admin_partner_request_decide',{p_id:r.id,p_decision:decision,p_note:note.trim(),p_firm_verified:verified,p_venue:r.kind==='new'?target.trim():null});done();}
 return <Card className="detail"><h2>{r.venue_name||r.details.venue_name||'Cerere de parteneriat'}</h2><Tag>{statusLabel[r.status]}</Tag><dl><dt>Cont solicitant</dt><dd>@{r.applicant_username||'cont șters'}</dd>{Object.entries(r.details).filter(([key])=>labels[key]).map(([key,value])=><div className="dl-pair" key={key}><dt>{labels[key]}</dt><dd>{value}</dd></div>)}</dl>{r.kind==='dispute'&&<div className="notice"><strong>Proprietarul actual: @{r.owner_username||'—'}</strong><p className="preserve">{r.owner_response||'Proprietarul nu a răspuns încă.'}</p><p>Termen răspuns: {date(r.owner_response_deadline||r.deadline||r.owner_deadline)}. Serverul verifică termenul înaintea deciziei.</p></div>}{r.proof_available&&<><button onClick={()=>setProof(!proof)}>{proof?'Închide dovada':'Vezi dovada'}</button>{proof&&<Photo id={r.id} proof/>}</>}{(r.decision_note||r.note)&&<p className="notice preserve">{r.decision_note||r.note}</p>}{may&&<form onSubmit={e=>{e.preventDefault();void a.run(()=>decide('verified'),'Dosarul a fost verificat.');}}>{r.kind==='new'&&<><label>ID local din catalog<input required maxLength={40} value={target} onChange={e=>setTarget(e.target.value)} placeholder="a-… sau identificatorul catalogului"/></label><PlacePicker onPick={setTarget}/></>}<label className="checkbox"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/>Am verificat manual firma, reprezentarea și documentul solicitantului.</label><label>Răspunsul deciziei<textarea aria-label="Răspunsul deciziei" value={note} onChange={e=>setNote(e.target.value)} required minLength={5} maxLength={1000} rows={4}/></label><Notice error={a.error} success={a.success}/><div className="actions"><button className="primary" disabled={a.busy||!verified||note.trim().length<5||!r.proof_available}>Verifică dosarul</button><button type="button" className="destructive" disabled={a.busy||note.trim().length<5} onClick={()=>void a.run(()=>decide('rejected'),'Cererea a fost respinsă.')}>Respinge cererea</button></div><p className="muted">Verificarea nu acordă proprietatea și nu activează contractul. Facturarea rămâne oprită până la configurarea circuitului fiscal.</p></form>}</Card>;
}
function PlacePicker({onPick}:{onPick:(v:string)=>void}){
 const [q,setQ]=useState('');const s=useData<Place[]>('admin_places',{p_query:q,p_limit:20,p_offset:0});
 return <details><summary>Caută localul în catalog</summary><label>Numele localului<input value={q} maxLength={100} onChange={e=>setQ(e.target.value)}/></label><Loading {...s}/>{s.data?.map(p=><button type="button" className="picker-row" key={p.id} onClick={()=>onPick(p.id)}>{p.name} · {p.id}</button>)}</details>;
}
export function Pagination({page,length,setPage}:{page:number;length:number;setPage:(v:number)=>void}){return <div className="actions pagination"><button disabled={page===0} onClick={()=>setPage(page-1)}>Înapoi</button><span className="muted">Pagina {page+1}</span><button disabled={length<50} onClick={()=>setPage(page+1)}>Înainte</button></div>;}
