import {useEffect,useState,type ReactNode} from 'react';
import {rpc,supabase,message} from './backend';
import {validateAttachment} from './photo';
export function Card({children,className=''}:{children:ReactNode;className?:string}){return <section className={'card '+className}>{children}</section>;}
export function Empty({children='Nicio cerere aici.'}:{children?:ReactNode}){return <div className="empty"><Bilu/><p>{children}</p></div>;}
export function Notice({error,success}:{error?:string;success?:string}){return <>{error&&<p className="notice danger" role="alert">{error}</p>}{success&&<p className="notice positive" role="status">{success}</p>}</>;}
export function Loading({error,loading}:{error:string;loading:boolean}){return <>{loading&&<p role="status" className="muted">Se încarcă…</p>}<Notice error={error}/></>;}
export function Tag({children,tone=''}:{children:ReactNode;tone?:string}){return <span className={'tag '+tone}>{children}</span>;}
export const statusLabel:Record<string,string>={new:'Nouă',in_progress:'În lucru',resolved:'Rezolvată',rejected:'Respinsă',draft:'Ciornă',pending:'În verificare',verified:'Verificată',cancelled:'Anulată',on:'Vizibil',hidden:'Ascuns',gone:'Dispărut',activ:'Activ',pauza:'În pauză',iesit:'Ieșit'};
export function date(v?:string|null){return v?new Date(v).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest',dateStyle:'medium',timeStyle:'short'}):'—';}
export function money(v:unknown){return new Intl.NumberFormat('ro-RO',{style:'currency',currency:'RON'}).format(Number(v)||0);}
export function Brand(){return <div className="brand"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2 9a3 3 0 0 1 0 6v2a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-2a3 3 0 0 1 0-6V7a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2Z" fill="#FFD43B"/><path d="M13 5v2M13 11v2M13 17v2" stroke="#0E1440" strokeWidth="1.8" strokeLinecap="round"/></svg><strong>CeFaci</strong><Tag tone="coral">Admin</Tag></div>;}
export function Icon({name}:{name:string}){const icons:Record<string,string>={launch:'M12 3v18M3 12h18M5 5l14 14M5 19 19 5',home:'m3 10 9-7 9 7M5 9v11h5v-6h4v6h5V9',requests:'M7 3h10l3 3v15H4V3h3Zm1 5h8M8 12h8M8 16h5',reports:'M12 3 2 20h20L12 3Zm0 6v5m0 3v.01',places:'M20 10c0 6-8 11-8 11S4 16 4 10a8 8 0 1 1 16 0ZM12 7a3 3 0 1 0 0 6 3 3 0 0 0 0-6',partners:'M3 7h18v14H3V7Zm4 0V3h10v4M3 12h18M9 12v3h6v-3',operations:'M5 12h14m-5-5 5 5-5 5M4 4v16',finance:'M3 5h18v14H3V5Zm9 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8',plus:'M12 3v18M3 12h18',suggestions:'M9 18h6M10 21h4M8 14a6 6 0 1 1 8 0c-1 1-1 2-1 3H9c0-1 0-2-1-3',people:'M12 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8M4 21v-2a8 8 0 0 1 16 0v2',staff:'M8 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8M2 21v-3a6 6 0 0 1 12 0v3M17 3a4 4 0 0 1 0 8M17 14a6 6 0 0 1 5 6',journal:'M6 3h12v18H6V3Zm3 5h6M9 12h6M9 16h4',sun:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5M17.5 17.5 19 19M5 19l1.5-1.5M17.5 6.5 19 5',moon:'M20 15A9 9 0 0 1 9 4 9 9 0 1 0 20 15Z',refresh:'M20 7v5h-5M4 17v-5h5M5.6 7a8 8 0 0 1 12.8-2L20 8M4 16l1.6 3A8 8 0 0 0 18.4 17'};return <svg className="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={icons[name]||icons.home}/></svg>;}
const biluImages={spring:new URL('../../mobile/assets/icons/primavara-fg.png',import.meta.url).href,summer:new URL('../../mobile/assets/icons/vara-fg.png',import.meta.url).href,fall:new URL('../../mobile/assets/icons/toamna-fg.png',import.meta.url).href,winter:new URL('../../mobile/assets/icons/iarna-fg.png',import.meta.url).href,christmas:new URL('../../mobile/assets/icons/craciun-fg.png',import.meta.url).href};
export function Bilu(){const now=new Date(),month=Number(new Intl.DateTimeFormat('en',{timeZone:'Europe/Bucharest',month:'numeric'}).format(now)),day=Number(new Intl.DateTimeFormat('en',{timeZone:'Europe/Bucharest',day:'numeric'}).format(now));const season=month===12||month===1&&day<=7?'christmas':month>=3&&month<=5?'spring':month>=6&&month<=8?'summer':month>=9&&month<=11?'fall':'winter';return <img className="bilu" src={biluImages[season]} alt="Bilu"/>;}
export function Photo({id,proof=false}:{id:string;proof?:boolean}){
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[url,setUrl]=useState(''),[pdf,setPdf]=useState(false);
  useEffect(()=>{let disposed=false;let held='';let timer:ReturnType<typeof setTimeout>|undefined;async function open(){setBusy(true);setError('');setUrl('');try{const g=await rpc<{bucket:string;path:string;expires_in:number}>(proof?'biz_partner_proof_access':'support_report_photo_access',{p_id:id});if(disposed)return;const {data,error}=await supabase.storage.from(g.bucket).download(g.path);if(error)throw error;if(disposed)return;const type=data.type.split(';')[0];if(!['image/jpeg','image/png',...(proof?['application/pdf']:[])].includes(type))throw new Error('Fișierul nu are un format sigur de afișat.');await validateAttachment(data,proof);if(disposed)return;held=URL.createObjectURL(data);setPdf(type==='application/pdf');setUrl(held);timer=setTimeout(()=>{URL.revokeObjectURL(held);if(!disposed){setUrl('');setError('Accesul temporar a expirat. Închide și redeschide atașamentul.');}},Math.min(g.expires_in,300)*1000);}catch(e){if(!disposed)setError(message(e));}finally{if(!disposed)setBusy(false);}}void open();return()=>{disposed=true;if(held)URL.revokeObjectURL(held);if(timer)clearTimeout(timer);};},[id,proof]);
  return <div className="attachment"><Loading error={error} loading={busy}/>{url&&(pdf?<a className="button" href={url} target="_blank" rel="noopener noreferrer">Deschide documentul PDF</a>:<img src={url} alt={proof?'Dovada solicitantului':'Poza problemei raportate'}/>)}<p className="muted">Atașament privat. Accesul este temporar și rămâne în jurnal.</p></div>;
}
