import { beforeAll, beforeEach, afterAll, it, expect } from 'vitest';
import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs';
let db:PGlite;
const U={client:'00000000-0000-0000-0000-000000000001',other:'00000000-0000-0000-0000-000000000002',owner:'00000000-0000-0000-0000-000000000003',admin:'00000000-0000-0000-0000-000000000004',support:'00000000-0000-0000-0000-000000000005',accountant:'00000000-0000-0000-0000-000000000006',noProfile:'00000000-0000-0000-0000-000000000007',founder:'00000000-0000-0000-0000-000000000008'};
const q=(sql:string,args:unknown[]=[])=>db.query<any>(sql,args);
async function as(who:keyof typeof U,sql:string,args:unknown[]=[]){await db.exec(`reset role;select set_config('request.jwt.claim.sub','${U[who]}',false);set role authenticated`);try{return await q(sql,args)}finally{await db.exec('reset role')}}
async function rpc(who:keyof typeof U,sql:string,args:unknown[]=[]){return (await as(who,`select ${sql} result`,args)).rows[0].result}
let sequence=0;
const create=(who:keyof typeof U='client',opts:any={})=>rpc(who,'support_report_create($1,$2,$3,$4,$5,$6,$7)',[opts.key??`request-${++sequence}`,opts.kind??'issue',opts.source??'client',opts.title??'Problemă de test',opts.description??'Nu pot vedea un rezultat în aplicație.',opts.venue??null,opts.mime??null]);
async function upload(r:any,who:keyof typeof U='client',metadata:any={size:1200,mimetype:'image/jpeg',eTag:'trusted-etag'}){await as(who,"insert into storage.objects(bucket_id,name,metadata) values('support-photos',$1,$2)",[r.photo_path,metadata]);return r.photo_path;}
async function submitted(who:keyof typeof U='client',opts:any={}){const r=await create(who,opts);if(r.photo_path)await upload(r,who,{size:1200,mimetype:opts.mime??'image/jpeg',eTag:'trusted-etag'});return rpc(who,'support_report_submit($1,$2)',[r.id,r.photo_path]);}
beforeAll(async()=>{
 db=new PGlite();
 await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;alter default privileges in schema public grant all on tables to anon,authenticated,service_role;alter default privileges in schema public grant all on functions to anon,authenticated,service_role;create schema auth;create table auth.users(id uuid primary key,created_at timestamptz default now());create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;create publication supabase_realtime;create schema storage;create table storage.buckets(id text primary key,name text,public boolean default false,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,metadata jsonb,created_at timestamptz default now(),unique(bucket_id,name));alter table storage.objects enable row level security;grant usage on schema storage to authenticated;grant select,insert,update,delete on storage.objects to authenticated;`);
 for(const f of fs.readdirSync('supabase/migrations').sort())await db.exec(fs.readFileSync('supabase/migrations/'+f,'utf8'));
 await db.exec('grant usage on schema public to anon,authenticated');
 for(const [name,id]of Object.entries(U)){await q('insert into auth.users(id) values($1)',[id]);if(name!=='noProfile')await as(name as keyof typeof U,"select complete_signup($1,$1,'2000-01-01')",[name]);}
 await db.exec(`insert into venues(id,name,cat,lat,lon,data) values('venue','Local Test','mancare',44,26,'{}'),('hidden','Ascuns','mancare',44,26,'{}');update venues set status='hidden' where id='hidden';insert into partners(venue_id,firm,cui,rate,activated_at,free_until) values('venue','Firm SRL','18547290',.1,current_date,current_date);`);
 await q("insert into partner_members(venue_id,user_id,role)values('venue',$1,'proprietar')",[U.owner]);
 await q("insert into staff(user_id,role) values($1,'admin'),($2,'suport'),($3,'contabil'),($4,'fondator')",[U.admin,U.support,U.accountant,U.founder]);
},60000);
beforeEach(async()=>{await q("update private.support_reports set created_at=now()-interval '2 days',status=case when status='draft' then 'cancelled' else status end");await q("update private.support_reports set status='resolved' where status in('new','in_progress')");});
afterAll(()=>db?.close());

it('denies anonymous and nonstaff Admin access, including direct private reports and logs',async()=>{
 await db.exec('set role anon');try{await expect(q('select support_reports()')).rejects.toThrow(/permission denied/);await expect(q('select admin_me()')).rejects.toThrow(/permission denied/)}finally{await db.exec('reset role')}
 await expect(rpc('client','admin_me()')).rejects.toThrow(/rezervat/);await expect(rpc('client','admin_dashboard()')).rejects.toThrow(/rezervat/);await expect(rpc('client','admin_support_reports()')).rejects.toThrow(/Nu ai voie/);
 for(const table of['support_reports','support_report_log','support_photo_access','legacy_report_log'])await expect(as('client',`select * from private.${table}`)).rejects.toThrow(/permission denied/);
 expect((await q("select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='private' and relname in('support_reports','support_report_log','support_photo_access','legacy_report_log') and not relrowsecurity")).rows).toEqual([]);
});
it('uses server identity and accepts Business Auth without inventing a Client profile',async()=>{
 const r=await create('noProfile',{source:'business'});expect(r.status).toBe('draft');expect((await q('select user_id from private.support_reports where id=$1',[r.id])).rows[0].user_id).toBe(U.noProfile);expect((await q('select * from profiles where id=$1',[U.noProfile])).rows).toEqual([]);
 await db.exec(`select set_config('request.jwt.claims','{"is_anonymous":true}',false)`);try{await expect(create()).rejects.toThrow(/Intră întâi/)}finally{await db.exec("select set_config('request.jwt.claims','{}',false)")}
});
it('validates mandatory fields, lengths, MIME and venue authorization',async()=>{
 await expect(create('client',{title:'ab'})).rejects.toThrow(/titlul/);await expect(create('client',{description:'scurt'})).rejects.toThrow(/titlul/);await expect(create('client',{title:'x'.repeat(121)})).rejects.toThrow(/titlul/);await expect(create('client',{description:'x'.repeat(4001)})).rejects.toThrow(/titlul/);await expect(create('client',{mime:'image/svg+xml'})).rejects.toThrow(/JPEG/);await expect(create('client',{source:'business',venue:'venue'})).rejects.toThrow(/Nu ai acces/);await expect(create('client',{venue:'hidden'})).rejects.toThrow(/disponibil/);await expect(create('client',{kind:'missing_place',source:'business'})).rejects.toThrow(/din Client/);
 const a=await create('owner',{source:'business',venue:'venue'});expect(a.venue_id).toBe('venue');await q("update partner_members set active=false where user_id=$1",[U.owner]);await expect(create('owner',{source:'business',venue:'venue'})).rejects.toThrow(/Nu ai acces/);await q("update partner_members set active=true where user_id=$1",[U.owner]);
});
it('creates idempotent immutable drafts and refuses key reuse with another payload',async()=>{
 const r=await create('client',{key:'same'});expect((await create('client',{key:'same'})).id).toBe(r.id);await expect(create('client',{key:'same',title:'Altă problemă'})).rejects.toThrow(/cheie/);expect((await q('select * from private.support_report_log where report_id=$1',[r.id])).rows).toHaveLength(1);
});
it('submits without a photo and retries without duplicating queue or journal',async()=>{
 const r=await create();const s=await rpc('client','support_report_submit($1)',[r.id]);expect(s.status).toBe('new');expect(s.photo_available).toBe(false);expect(s.version).toBe(2);expect((await rpc('client','support_report_submit($1)',[r.id])).id).toBe(r.id);expect((await q("select * from private.support_report_log where report_id=$1 and action='submitted'",[r.id])).rows).toHaveLength(1);
});
it('prevents IDOR for submit, cancel, history and photo authorization',async()=>{
 const r=await create('client',{mime:'image/jpeg'});await upload(r);expect((await rpc('other','support_reports()')).some((x:any)=>x.id===r.id)).toBe(false);await expect(rpc('other','support_report_submit($1,$2)',[r.id,r.photo_path])).rejects.toThrow(/disponibil/);await expect(rpc('other','support_report_cancel($1)',[r.id])).rejects.toThrow(/disponibil/);await expect(rpc('other','support_report_photo_access($1)',[r.id])).rejects.toThrow(/disponibil/);await expect(rpc('admin','support_report_photo_access($1)',[r.id])).rejects.toThrow(/disponibil/);
});
it('protects optional upload paths and forbids replacement, deletion and reads without fresh access',async()=>{
 const b=(await q("select * from storage.buckets where id='support-photos'")).rows[0];expect(b.public).toBe(false);expect(Number(b.file_size_limit)).toBe(5242880);expect(b.allowed_mime_types).toEqual(['image/jpeg','image/png']);const r=await create('client',{mime:'image/jpeg'});await expect(upload(r,'other')).rejects.toThrow(/row-level security/);await expect(as('client',"insert into storage.objects(bucket_id,name,metadata)values('support-photos',$1,'{}')",[r.photo_path.replace('jpg','png')])).rejects.toThrow(/row-level security/);await upload(r);expect((await as('client','select * from storage.objects where name=$1',[r.photo_path])).rows).toEqual([]);expect((await as('client','update storage.objects set metadata=$1 where name=$2',[{},r.photo_path])).affectedRows).toBe(0);expect((await as('client','delete from storage.objects where name=$1',[r.photo_path])).affectedRows).toBe(0);
});
it('requires actual upload and validates stored size/MIME before accepting a photo',async()=>{
 const r=await create('client',{mime:'image/jpeg'});await expect(rpc('client','support_report_submit($1,$2)',[r.id,r.photo_path])).rejects.toThrow(/Încarcă/);await upload(r,'client',{size:5242881,mimetype:'image/jpeg'});await expect(rpc('client','support_report_submit($1,$2)',[r.id,r.photo_path])).rejects.toThrow(/5 MB/);await q('update storage.objects set metadata=$1 where name=$2',[{size:100,mimetype:'text/html'},r.photo_path]);await expect(rpc('client','support_report_submit($1,$2)',[r.id,r.photo_path])).rejects.toThrow(/JPEG/);await q('update storage.objects set metadata=$1 where name=$2',[{size:100,mimetype:'image/jpeg',eTag:'abc'},r.photo_path]);const s=await rpc('client','support_report_submit($1,$2)',[r.id,r.photo_path]);expect(s.photo_available).toBe(true);expect(s.photo_path).toBeNull();expect((await q('select photo_fingerprint from private.support_reports where id=$1',[r.id])).rows[0].photo_fingerprint).toBe('abc');await expect(upload({...r,photo_path:r.photo_path.replace('jpg','png')})).rejects.toThrow(/row-level security/);
});
it('authorizes private 5-minute photo access and checks current staff role on every read',async()=>{
 const r=await submitted('client',{mime:'image/jpeg'});await expect(rpc('accountant','support_report_photo_access($1)',[r.id])).rejects.toThrow(/disponibil/);const a=await rpc('support','support_report_photo_access($1)',[r.id]);expect(a.expires_in).toBe(300);expect(a.bucket).toBe('support-photos');expect((await as('support','select * from storage.objects where name=$1',[a.path])).rows).toHaveLength(1);await q('delete from staff where user_id=$1',[U.support]);expect((await as('support','select * from storage.objects where name=$1',[a.path])).rows).toEqual([]);await expect(rpc('support','admin_support_reports()')).rejects.toThrow(/Nu ai voie/);await q("insert into staff(user_id,role) values($1,'suport')",[U.support]);await q("update private.support_photo_access set expires_at=now()-interval '1 minute' where report_id=$1",[r.id]);expect((await as('support','select * from storage.objects where name=$1',[a.path])).rows).toEqual([]);
});
it('shows legacy and new missing places together while users see only their own reports and answers',async()=>{
 await as('client',"insert into reports(venue_id,kind,note)values('nou','altceva','LOC NOU: Cafenea · Buftea')");const r=await submitted('client',{kind:'missing_place',title:'Cafeneaua Nouă',description:'Strada Nouă 10, Buftea'});const queue=await rpc('admin','admin_support_reports($1,$2)',['new','missing_place']);expect(queue.some((x:any)=>x.origin==='legacy'&&x.description.includes('LOC NOU'))).toBe(true);expect(queue.some((x:any)=>x.origin==='support'&&x.id===r.id)).toBe(true);const own=await rpc('client','support_reports()');expect(own.some((x:any)=>x.origin==='legacy'&&x.kind==='missing_place')).toBe(true);expect((await rpc('other','support_reports()')).some((x:any)=>x.id===r.id)).toBe(false);
});
it('allows support triage with public answers, audit and optimistic revision without legacy-close authority',async()=>{
 const r=await submitted();const a=await rpc('support','admin_support_report_update($1,$2,$3,$4)',[r.id,'in_progress','Verificăm problema.',r.version]);expect(a.version).toBe(3);expect((await rpc('support','admin_support_report_update($1,$2,$3,$4)',[r.id,'in_progress','Verificăm problema.',r.version])).version).toBe(3);await expect(rpc('admin','admin_support_report_update($1,$2,$3,$4)',[r.id,'resolved','Am reparat problema.',r.version])).rejects.toThrow(/între timp/);await expect(rpc('support','admin_support_report_update($1,$2,$3,$4)',[r.id,'resolved','',a.version])).rejects.toThrow(/răspuns/);const done=await rpc('support','admin_support_report_update($1,$2,$3,$4)',[r.id,'resolved','Am reparat problema.',a.version]);expect(done.status).toBe('resolved');expect((await rpc('client','support_reports()')).find((x:any)=>x.id===r.id).answer).toBe('Am reparat problema.');expect((await q("select * from private.support_report_log where report_id=$1 and action='staff_updated'",[r.id])).rows).toHaveLength(2);await expect(rpc('client','admin_support_report_update($1,$2,$3,$4)',[r.id,'new',null,done.version])).rejects.toThrow(/Nu ai voie/);await expect(rpc('accountant','admin_support_report_update($1,$2,$3,$4)',[r.id,'new',null,done.version])).rejects.toThrow(/Nu ai voie/);
});
it('keeps legacy insert API and safely closes legacy rows with auditable revision and invalid-state guards',async()=>{
 await as('client',"insert into reports(venue_id,kind,note)values('nou','altceva','LOC NOU: Legacy')");
 // Insert-only callers do not get a SELECT policy, so fixture reads the id as server.
 const target=(await q("select id from reports where note='LOC NOU: Legacy'")).rows[0].id;
 await expect(rpc('support','admin_legacy_report_update($1,$2,$3,$4)',[target,'resolved','Locul a fost verificat.',1])).rejects.toThrow(/Nu ai voie/);await expect(rpc('admin','admin_report_close($1,$2)',[target,null])).rejects.toThrow(/Stare/);await expect(rpc('admin','admin_legacy_report_update($1,$2,$3,$4)',[target,'resolved','Locul a fost verificat.',null])).rejects.toThrow(/răspuns/);const s=await rpc('admin','admin_legacy_report_update($1,$2,$3,$4)',[target,'resolved','Locul a fost verificat.',1]);expect(s.status).toBe('resolved');expect(s.version).toBe(2);await expect(rpc('admin','admin_legacy_report_update($1,$2,$3,$4)',[target,'rejected','Nu este un loc disponibil.',1])).rejects.toThrow(/între timp/);await rpc('admin','admin_report_close($1,$2)',[target,'respins']);expect((await q('select count(*) n from private.legacy_report_log where report_id=$1',[target])).rows[0].n).toBe(2);
});
it('returns role-limited dashboard and catalogs without leaking unauthorized queue counts',async()=>{
 const admin=await rpc('admin','admin_me()');expect(admin.role).toBe('admin');expect(admin.permissions).toContain('partners');const support=await rpc('support','admin_me()');expect(support.role).toBe('suport');expect(support.permissions).toContain('support.manage');expect(support.permissions).not.toContain('reports.close');const account=await rpc('accountant','admin_dashboard()');expect(account.support_new).toBeNull();expect(account.partner_pending).toBeNull();expect((await rpc('admin','admin_places()')).some((x:any)=>x.id==='hidden'&&x.status==='hidden')).toBe(true);await expect(rpc('client','admin_places()')).rejects.toThrow(/rezervat/);await expect(rpc('support','admin_partner_requests()')).rejects.toThrow(/Doar echipa/);
});
it('allows cancel only for own draft, enforces expiry and server request quotas',async()=>{
 const r=await create();expect((await rpc('client','support_report_cancel($1)',[r.id])).status).toBe('cancelled');expect((await rpc('client','support_report_cancel($1)',[r.id])).status).toBe('cancelled');const s=await submitted();await expect(rpc('client','support_report_cancel($1)',[s.id])).rejects.toThrow(/deja/);const expired=await create();await q("update private.support_reports set created_at=now()-interval '2 days' where id=$1",[expired.id]);await expect(rpc('client','support_report_submit($1)',[expired.id])).rejects.toThrow(/nouă/);for(let i=0;i<9;i++)await create();await expect(create()).rejects.toThrow(/destule/);
});
it('expires photo access after 90 days and requires service-only Storage API deletion acknowledgement',async()=>{
 const r=await submitted('client',{mime:'image/jpeg'});const path=(await q('select photo_path from private.support_reports where id=$1',[r.id])).rows[0].photo_path;await q("update private.support_reports set photo_uploaded_at=now()-interval '91 days' where id=$1",[r.id]);await q("update storage.objects set created_at=now()-interval '91 days' where name=$1",[path]);await expect(rpc('admin','support_report_photo_access($1)',[r.id])).rejects.toThrow(/disponibil/);await expect(rpc('admin','support_photos_retention_candidates()')).rejects.toThrow(/permission denied/);await db.exec('set role service_role');try{expect((await q('select support_photos_retention_candidates() result')).rows[0].result).toContainEqual({report_id:r.id,path});await expect(q('select support_photo_deleted($1)',[r.id])).rejects.toThrow(/API-ul Storage/)}finally{await db.exec('reset role')};await q('delete from storage.objects where name=$1',[path]);await db.exec('set role service_role');try{await q('select support_photo_deleted($1)',[r.id])}finally{await db.exec('reset role')};expect((await q('select photo_deleted_at,photo_fingerprint from private.support_reports where id=$1',[r.id])).rows[0].photo_fingerprint).toBe('trusted-etag');
});
it('preserves immutable audit while allowing account deletion and anonymizing actor references',async()=>{
 const r=await submitted('noProfile',{source:'business'});await expect(q("update private.support_report_log set action='rewritten' where report_id=$1",[r.id])).rejects.toThrow(/nu se poate modifica/);await expect(q('delete from private.support_report_log where report_id=$1',[r.id])).rejects.toThrow(/nu se poate modifica/);await q('delete from auth.users where id=$1',[U.noProfile]);expect((await q('select user_id from private.support_reports where id=$1',[r.id])).rows[0].user_id).toBeNull();expect((await q('select by_user from private.support_report_log where report_id=$1',[r.id])).rows.every((x:any)=>x.by_user===null)).toBe(true);
});

it('requires optimistic audited staff changes and forbids legacy staff API bypass',async()=>{
 await expect(rpc('admin','staff_set($1,$2)',[U.other,'editor'])).rejects.toThrow(/permission denied/);await expect(rpc('admin','staff_remove($1)',[U.other])).rejects.toThrow(/permission denied/);await expect(rpc('support','admin_staff_change($1,$2,$3)',[U.other,'editor','Ajută echipa de locuri.'])).rejects.toThrow(/Nu ai voie/);const added=await rpc('admin','admin_staff_change($1,$2,$3,$4)',[U.other,'editor','Ajută echipa de locuri.',null]);expect(added.role).toBe('editor');await expect(rpc('admin','admin_staff_change($1,$2,$3,$4)',[U.other,'moderator','Ajută echipa de semnalări.',null])).rejects.toThrow(/între timp/);await expect(rpc('admin','admin_staff_change($1,$2,$3,$4)',[U.other,'admin','Devine administrator.', 'editor'])).rejects.toThrow(/doar editori/);await expect(rpc('admin','admin_staff_change($1,$2,$3,$4)',[U.admin,'editor','Schimbare proprie.', 'admin'])).rejects.toThrow(/singur rolul/);const changed=await rpc('admin','admin_staff_change($1,$2,$3,$4)',[U.other,'moderator','Ajută echipa de semnalări.','editor']);expect(changed.role).toBe('moderator');const removed=await rpc('admin','admin_staff_change($1,$2,$3,$4)',[U.other,null,'Nu mai face parte din echipă.','moderator']);expect(removed.removed).toBe(true);expect((await q('select count(*) n from private.admin_staff_log where target_user=$1',[U.other])).rows[0].n).toBe(3);await expect(q("update private.admin_staff_log set note='Rescriere' where target_user=$1",[U.other])).rejects.toThrow(/nu se poate modifica/);
});
it('restricts staff lookup to exact usernames and gives no sensitive customer profile fields',async()=>{
 await expect(rpc('support','admin_staff_search($1)',['client'])).rejects.toThrow(/Nu ai voie/);await expect(rpc('admin','admin_staff_search($1)',['cl'])).rejects.toThrow(/username/);expect(await rpc('admin','admin_staff_search($1)',['@client'])).toEqual([{user_id:U.client,username:'client'}]);expect(await rpc('admin','admin_staff_search($1)',['clie'])).toEqual([]);expect((await rpc('support','admin_staff_list()')).find((x:any)=>x.user_id===U.admin)).toMatchObject({role:'admin',username:'admin'});
});
it('restricts audit data and partner-sensitive venue logs according to current permissions',async()=>{
 await q("insert into venue_log(venue_id,by_user,action,after)values('venue',$1,'partener','{\"firm\":\"Secret SRL\",\"cui\":\"18547290\"}'),('venue',$1,'edit','{\"name\":\"Local Public\"}')",[U.admin]);await expect(rpc('accountant',"admin_place_log('venue')")).rejects.toThrow(/Nu ai voie/);await expect(rpc('support',"admin_place_log('venue')")).rejects.toThrow(/Nu ai voie/);await q("insert into staff(user_id,role)values($1,'editor')",[U.other]);const editorlog=await rpc('other',"admin_place_log('venue')");expect(editorlog.every((x:any)=>x.action!=='partener')).toBe(true);await q('delete from staff where user_id=$1',[U.other]);expect((await rpc('admin',"admin_place_log('venue')")).some((x:any)=>x.action==='partener')).toBe(true);await expect(rpc('support','admin_activity()')).rejects.toThrow(/Nu ai voie/);const activity=await rpc('admin','admin_activity()');expect(activity.some((x:any)=>x.origin==='staff')).toBe(true);expect(activity.some((x:any)=>x.origin==='support')).toBe(true);expect(activity.every((x:any)=>!('data' in x)&&!('note' in x)&&!('description' in x))).toBe(true);
});

it('enforces permission filtering on direct venue_log REST reads as well as the wrapper',async()=>{
 expect((await as('support',"select * from venue_log where venue_id='venue'")).rows).toEqual([]);expect((await as('accountant',"select * from venue_log where venue_id='venue'")).rows).toEqual([]);
 await q("insert into staff(user_id,role)values($1,'editor')",[U.other]);let rows=(await as('other',"select * from venue_log where venue_id='venue'")).rows;expect(rows.length).toBeGreaterThan(0);expect(rows.every((r:any)=>r.action!=='partener')).toBe(true);await q("update staff set role='moderator' where user_id=$1",[U.other]);rows=(await as('other',"select * from venue_log where venue_id='venue'")).rows;expect(rows.every((r:any)=>r.action!=='partener')).toBe(true);await q('delete from staff where user_id=$1',[U.other]);expect((await as('admin',"select * from venue_log where venue_id='venue' and action='partener'")).rows.length).toBeGreaterThan(0);
});
it('resets forged legacy lifecycle fields and enforces the shared daily reporting quota',async()=>{
 await q("update reports set created_at=now()-interval '2 days' where user_id=$1",[U.client]);
 await as('client',"insert into reports(venue_id,kind,note,status,handled_by,handled_at,answer,revision,created_at)values('nou','altceva','Forged legacy','rezolvat',$1,now(),'Already approved',999,now()+interval '5 years')",[U.admin]);const row=(await q("select * from reports where note='Forged legacy'")).rows[0];expect(row.status).toBe('nou');expect(row.handled_by).toBeNull();expect(row.handled_at).toBeNull();expect(row.answer).toBeNull();expect(row.revision).toBe(1);expect(new Date(row.created_at).getUTCFullYear()).toBe(new Date().getUTCFullYear());
 await db.exec(`select set_config('request.jwt.claims','{"is_anonymous":true}',false)`);try{await expect(as('client',"insert into reports(venue_id,kind)values('nou','altceva')")).rejects.toThrow(/Intră întâi/)}finally{await db.exec("select set_config('request.jwt.claims','{}',false)")}
 for(let i=0;i<9;i++){const r=await create();await rpc('client','support_report_cancel($1)',[r.id]);}
 for(let i=0;i<10;i++)await as('client',"insert into reports(venue_id,kind)values('nou','altceva')");await expect(create()).rejects.toThrow(/destule/);await expect(as('client',"insert into reports(venue_id,kind)values('nou','altceva')")).rejects.toThrow(/destule/);
});
it('does not permit manual audit actor nullification but permits FK account anonymization',async()=>{
 const report=await submitted('other');await expect(q('update private.support_report_log set by_user=null where report_id=$1',[report.id])).rejects.toThrow(/nu se poate modifica/);await expect(q('update private.admin_staff_log set by_user=null where by_user=$1',[U.admin])).rejects.toThrow(/nu se poate modifica/);
 await q("insert into auth.users(id)values('00000000-0000-0000-0000-00000000000a')");await q("insert into private.admin_staff_log(target_user,by_user,previous_role,next_role,note)values('00000000-0000-0000-0000-00000000000a','00000000-0000-0000-0000-00000000000a',null,'editor','Test FK anonymization')");await q("delete from auth.users where id='00000000-0000-0000-0000-00000000000a'");expect((await q("select target_user,by_user from private.admin_staff_log where note='Test FK anonymization'")).rows[0]).toEqual({target_user:null,by_user:null});
});
