import {beforeAll,beforeEach,afterAll,it,expect} from 'vitest';
import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';
import {createHash,randomUUID} from 'node:crypto';
import {prepareAuthSchema,seedAuthFixture,authenticateFixture} from './fixtures/auth.mjs';
let db:PGlite;
const A='99000000-0000-0000-0000-000000000011';
const q=(sql:string,args:unknown[]=[])=>db.query<any>(sql,args);
function proof(token:string){for(let i=0;;i++)if(createHash('sha256').update(token+':'+i).digest('hex').startsWith('000'))return ''+i;}
async function anon(sql:string,args:unknown[]=[]){await db.exec('set role anon');try{return(await q(sql,args)).rows[0]?.r;}finally{await db.exec('reset role');}}
async function admin(sql:string,args:unknown[]=[],scopes=true){await authenticateFixture(db,A,{scopes});await db.exec('set role authenticated');try{return(await q(sql,args)).rows[0]?.r;}finally{await db.exec('reset role');}}
const withdraw=(token:string)=>anon('select launch_interest_withdraw($1,$2)r',[token,proof(token)]);
const submit=(token=randomUUID(),vote='yes',name='Bilu tester',email:string|null=null,consent=false,feedback=true)=>anon('select launch_interest_submit($1,$2,$3,$4,$5,$6,$7)r',[token,proof(token),vote,name,email,consent,feedback]);
beforeAll(async()=>{db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;alter default privileges in schema public grant all on tables to anon,authenticated,service_role;alter default privileges in schema public grant all on functions to anon,authenticated,service_role;create schema auth;create table auth.users(id uuid primary key,created_at timestamptz default now());create function auth.uid()returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid()to authenticated;create publication supabase_realtime;`);await prepareAuthSchema(db);for(const file of fs.readdirSync('supabase/migrations').sort())await db.exec(fs.readFileSync('supabase/migrations/'+file,'utf8'));await db.exec('grant usage on schema public to anon,authenticated');await q('insert into auth.users(id)values($1)',[A]);await seedAuthFixture(db,A);await admin("select complete_signup('quizadmin','quizadmin','2000-01-01')r",[],false);await q("insert into staff(user_id,role)values($1,'admin')",[A]);},60000);
beforeEach(async()=>{await db.exec('truncate private.launch_interests,private.launch_quotas,private.launch_withdrawals,private.security_sessions');await q("update staff set role='admin'where user_id=$1",[A]);await seedAuthFixture(db,A);});
afterAll(()=>db?.close());
it('accepts every vote with an alias and no email; responses never echo personal data',async()=>{for(const vote of ['yes','maybe','no'])expect(await submit(undefined,vote)).toEqual({saved:true,email_requested:false});expect((await q('select count(*)::int n from private.launch_interests')).rows[0].n).toBe(3);});
it('requires explicit independent consent and validates on server',async()=>{for(const args of [[undefined,'yes','Tester','test@example.test',false],[undefined,'yes','Tester',null,true],[undefined,'yes','Tester','invalid',true],[undefined,'yes','Tester',null,false,false],[undefined,'invalid'],[undefined,'yes','<script>'],[undefined,'yes','  ']] as any[])await expect(submit(...args)).rejects.toThrow();expect(await submit(undefined,'no','Tester',' TEST@example.test ',true)).toEqual({saved:true,email_requested:true});const r=(await q('select email,consent_text,email_consent_at from private.launch_interests')).rows[0];expect(r.email).toBe('test@example.test');expect(r.consent_text).toContain('Vreau să primesc un email');expect(r.email_consent_at).toBeTruthy();});
it('rejects missing proof and honeypot; idempotent immutable receipts',async()=>{const token=randomUUID();await expect(anon("select launch_interest_submit($1,'wrong','yes','Tester',null,false,true)r",[token])).rejects.toThrow();await expect(anon("select launch_interest_submit($1,$2,'yes','Tester',null,false,true,'spam')r",[token,proof(token)])).rejects.toThrow();const first=await submit(token);expect(await submit(token)).toEqual(first);await expect(submit(token,'no')).rejects.toThrow(/inițială/);expect((await q('select count(*)::int n from private.launch_interests')).rows[0].n).toBe(1);});
it('public roles cannot read private data or call admin endpoints',async()=>{await submit();for(const sql of ['select * from private.launch_interests','select * from private.launch_quotas','select admin_launch_interests()','select admin_launch_interest_delete(gen_random_uuid())'])await expect(anon(sql)).rejects.toThrow();const r=await admin('select admin_launch_interests()r');expect(r.summary.total).toBe(1);expect(r.rows[0].name).toBe('Bilu tester');expect(r.rows[0]).not.toHaveProperty('receipt_hash');});
it('admin role, live session and MFA are all required, including after downgrade',async()=>{await submit();await expect(admin('select admin_launch_interests()r',[],false)).rejects.toThrow();for(const role of ['editor','moderator','suport','contabil']){await q('update staff set role=$1 where user_id=$2',[role,A]);await expect(admin('select admin_launch_interests()r')).rejects.toThrow();await expect(admin('select admin_launch_interest_delete(gen_random_uuid())r')).rejects.toThrow();}await q("update staff set role='fondator'where user_id=$1",[A]);expect((await admin('select admin_launch_interests()r')).summary.total).toBe(1);await q('delete from auth.sessions where user_id=$1',[A]);await expect(admin('select admin_launch_interests()r')).rejects.toThrow();});
it('private withdrawal removes all submitted data and does not enumerate receipts',async()=>{const a=randomUUID(),b=randomUUID();await submit(a,'yes','Ana','ana@example.test',true);await submit(b,'no','Bob');expect(await withdraw(randomUUID())).toEqual({withdrawn:true});expect(await withdraw(a)).toEqual({withdrawn:true});expect(await withdraw(a)).toEqual({withdrawn:true});const r=await admin('select admin_launch_interests()r');expect(r.summary.total).toBe(1);expect(r.rows[0].name).toBe('Bob');await admin('select admin_launch_interest_delete($1)r',[r.rows[0].id]);expect((await admin('select admin_launch_interests()r')).summary.total).toBe(0);});
it('quota survives withdrawals, retries do not consume quota, expiry hides stale data',async()=>{const token=randomUUID();await submit(token);await submit(token);expect((await q('select sum(submissions)::int n from private.launch_quotas')).rows[0].n).toBe(1);await withdraw(token);await q('update private.launch_quotas set submissions=100');await expect(submit()).rejects.toThrow(/prea multe/);await q('update private.launch_quotas set submissions=1');await submit();await q("update private.launch_interests set expires_at=now()-interval '1 day'");expect((await admin('select admin_launch_interests()r')).summary.total).toBe(0);});
it('filters use literal text and bounded pages, never SQL fragments or wildcard expansion',async()=>{await submit(undefined,'yes','100% real');await submit(undefined,'no','Other');expect((await admin("select admin_launch_interests(null,'%',0)r")).rows).toHaveLength(1);expect((await admin("select admin_launch_interests('no','',0)r")).rows).toHaveLength(1);await expect(admin("select admin_launch_interests(null,'',-1)r")).rejects.toThrow();});

it('withdrawal blocks delayed requests and idempotent replay from resurrecting consent',async()=>{const token=randomUUID();await withdraw(token);await expect(submit(token)).rejects.toThrow(/retrasă/);const b=randomUUID();await submit(b);await withdraw(b);await expect(submit(b)).rejects.toThrow(/retrasă/);expect((await admin('select admin_launch_interests()r')).summary.total).toBe(0);});
