import { expect,it } from 'vitest';
// @ts-expect-error Server-only JavaScript runner.
import { retainSupportPhotos } from '../scripts/retain-support-photos.mjs';
const id='00000000-0000-0000-0000-000000000002',path=`00000000-0000-0000-0000-000000000001/${id}/photo.jpg`;
function fixture(data:any){const calls:any[]=[];return {calls,fetcher:async(url:string,opts:any)=>{calls.push({url,method:opts.method,body:JSON.parse(opts.body)});return {ok:true,status:200,json:async()=>calls.length===1?data:[]};}};}
it('support photo retention defaults to dry-run',async()=>{const f=fixture([{report_id:id,path}]);expect(await retainSupportPhotos({key:'synthetic-server-key',fetcher:f.fetcher})).toEqual({mode:'dry-run',files:1});expect(f.calls).toHaveLength(1);});
it('support retention deletes through Storage API before acknowledging',async()=>{const f=fixture([{report_id:id,path}]);expect(await retainSupportPhotos({key:'synthetic-server-key',execute:true,fetcher:f.fetcher})).toEqual({mode:'execute',files:1});expect(f.calls.map(c=>c.method)).toEqual(['POST','DELETE','POST']);expect(f.calls[1].body).toEqual({prefixes:[path]});expect(f.calls[2].body).toEqual({p_id:id});});
it('support retention does not acknowledge failed physical deletion',async()=>{const f=fixture([{report_id:id,path}]);const fetcher=async(url:string,opts:any)=>{const r=await f.fetcher(url,opts);return f.calls.length===2?{...r,ok:false,status:503}:r;};await expect(retainSupportPhotos({key:'synthetic-server-key',execute:true,fetcher})).rejects.toThrow(/503/);expect(f.calls).toHaveLength(2);});
it('support retention rejects foreign or malformed paths before deletion',async()=>{for(const c of [{report_id:id,path:'other-bucket/photo.jpg'},{report_id:id,path:path.replace(id,'00000000-0000-0000-0000-000000000003')}]){const f=fixture([c]);await expect(retainSupportPhotos({key:'synthetic-server-key',execute:true,fetcher:f.fetcher})).rejects.toThrow(/Invalid retention/);expect(f.calls).toHaveLength(1);}});
