import { LEGAL_CONTACT_EMAIL, LEGAL_OPERATOR, LEGAL_VERSION } from './legal-config';
export { LEGAL_CONTACT_EMAIL, LEGAL_OPERATOR, LEGAL_VERSION, LEGAL_LINKS } from './legal-config';
export type LegalAudience = 'client' | 'business' | 'admin' | 'website';
export type LegalSection = { title: string; paragraphs: string[] };
export type LegalDocument = { id: string; title: string; path: string; audience: LegalAudience[]; sections: LegalSection[] };
const email = LEGAL_CONTACT_EMAIL;
const operator = `Proiect CeFaci este în dezvoltare și beta, înaintea lansării comerciale. Contact: ${email}. Nu există încă o firmă înregistrată pentru CeFaci. Identitatea completă și adresa operatorului urmează să fie completate înaintea lansării; aceste date nu sunt publicate în prezent. Informarea este provizorie în privința identității, nu o declarație de îndeplinire completă a cerințelor legale. Obligațiile de protecție a datelor se aplică și în această etapă.`;
const rights = `Poți solicita acces, copie, corectare, ștergere, restricționare și, când sunt îndeplinite condițiile legale, portabilitate și opoziție, la ${email}. Poți retrage un consimțământ fără a afecta prelucrarea anterioară. Răspundem fără întârzieri nejustificate, în cel mult o lună calendaristică de la primirea cererii. Pentru cereri complexe sau numeroase, termenul poate fi prelungit cu încă două luni; îți comunicăm prelungirea și motivele în prima lună. Verificăm identitatea proporțional, fără a solicita automat un act de identitate.`;
export const LEGAL_DOCUMENTS: LegalDocument[] = [
  { id: 'privacy', title: 'Politica de confidențialitate', path: '/confidentialitate/', audience: ['client','business','admin','website'], sections: [
    { title: '1. Cine răspunde de date', paragraphs: [operator, 'Această informare acoperă site-ul cefaci.app, aplicația Client, Business și dashboardul Admin. Localurile pot avea propriile obligații de operator pentru rezervări, servire și evidențe legale; informarea lor se aplică separat acelor activități. Un eventual rol de împuternicit al CeFaci pentru un local necesită un acord distinct, nu rezultă automat din folosirea Business.'] },
    { title: '2. Cont, profil și funcțiile sociale', paragraphs: ['Folosim adresa de e-mail, identificatorul contului și informațiile furnizate la autentificarea Google, prenumele, username-ul, data nașterii, preferințele declarate și starea salvată în aplicație. E-mailul sau Google permit autentificarea; numele, prietenii, găștile, invitațiile, planurile, voturile, biletele, XP-ul și ștampilele permit funcțiile cerute de tine. Temeiul este executarea serviciului solicitat, art. 6 alin. (1) lit. b GDPR.', 'Data nașterii verifică limita de 16 ani a produsului și filtrele pentru locurile 18+. Aceasta este o regulă de eligibilitate și protecție a minorilor a CeFaci, nu o afirmație că legea impune universal vârsta de 16 ani pentru orice serviciu. Nu publicăm data nașterii în profilul social. Prietenii și participanții văd informațiile necesare colaborării, precum prenumele, username-ul, voturile, planul și progresul afișat.', 'Fără cont, preferințele și progresul nesincronizat se păstrează pe dispozitiv. Cererile de catalog și încărcarea site-ului pot totuși genera date tehnice la furnizori, inclusiv adresa IP; modul fără cont nu înseamnă că nu există nicio prelucrare pe server.'] },
    { title: '3. Locație și verificarea unei vizite', paragraphs: ['Locația se solicită în momentul în care alegi o funcție care are nevoie de ea. Nu solicităm urmărire permanentă în fundal. Poți refuza permisiunea și poți alege manual zona pentru funcțiile care permit acest lucru.', 'Punctul de referință ales în profil poate fi sincronizat cu contul după rotunjirea coordonatelor la trei zecimale, aproximativ 100 de metri. La confirmarea sosirii, revendicarea unui Drop sau verificarea eligibilității unei vizite, coordonatele precise și, în anumite fluxuri, precizia măsurării sunt transmise serverului pentru validarea apropierii. Nu este corect să spunem că toate coordonatele rămân exclusiv pe telefon.', 'Permisiunea dispozitivului permite accesul la locație. Pentru verificarea punctuală solicitată, prelucrarea este necesară funcției cerute; opțiunile facultative bazate pe consimțământ pot fi retrase. Nu folosim locația pentru publicitate sau pentru a comercializa trasee.'] },
    { title: '4. Bonuri, imagini, suport și cereri de local', paragraphs: ['Când alegi citirea unui bon, fotografia este transmisă funcției de procesare și, dacă serviciul este configurat, Google Cloud Vision pentru extragerea CUI-ului, datei, orei, totalului și reducerii. Implementarea nu salvează fotografia bonului în bucketul de suport; păstrează câmpurile extrase și o amprentă pentru verificarea vizitei și prevenirea reutilizării. Funcția poate fi indisponibilă dacă furnizorul OCR nu este activat. Nu trimite date de card, CNP sau informații fără legătură cu bonul.', 'Aplicația Client permite alegerea explicită a unei imagini prin selectorul sistemului pentru funcțiile care o cer. Nu solicită acces general la galeria telefonului. Camera și locația sunt solicitate punctual pentru funcția aleasă; alegerea sau refuzul se gestionează și în permisiunile dispozitivului.', 'Poza atașată unei probleme și documentul care dovedește legătura cu un local sunt fișiere distincte, păstrate în spații private. O solicitare Business poate conține numele și rolul reprezentantului, telefonul, firma, CUI-ul, adresa localului și dovada reprezentării. Încarcă doar documentele necesare, cu informațiile nerelevante mascate. Nu solicităm automat copii integrale de acte de identitate.', 'Folosim conținutul problemei, cererii și răspunsurilor pentru soluționare și verificare, pe baza serviciului solicitat și a interesului legitim de securitate, prevenire a fraudei și apărare a drepturilor. Textul liber poate conține date personale chiar după eliminarea legăturii cu un cont; îl evaluăm separat la o cerere de ștergere.'] },
    { title: '5. Business și Admin', paragraphs: ['Prelucrăm apartenența la echipă, rolul, localul autorizat, rezervările și vizitele relevante, numărul de persoane, stările, confirmările și informațiile despre reduceri sau estimările financiare. Aceste date sunt afișate numai rolurilor autorizate, pentru operarea serviciului și controlul deciziilor. Un membru al unui local nu primește acces la toate datele platformei.', 'Admin utilizează identitatea profesională, rolurile, deciziile și jurnalul acțiunilor pentru suport, parteneri, moderare, verificare și control financiar, conform drepturilor atribuite. Datele de autentificare, factorii MFA și identificatorii sesiunilor privilegiate susțin securitatea. Interesul legitim de protejare a serviciului nu justifică folosirea datelor în scopuri personale sau monitorizarea fără limită a angajaților.'] },
    { title: '6. Date tehnice, recomandări și proba Plus', paragraphs: ['Furnizorii pot procesa IP-ul, informații despre dispozitiv/browser, ora cererii, erori și jurnale de securitate. Acestea susțin funcționarea și protecția serviciului, pe baza interesului legitim. Nu activăm statistici de marketing sau pixeli publicitari în această versiune.', 'Recomandările folosesc zona, interesele, bugetul și opțiunile tale pentru ordonarea localurilor. Nu sunt decizii exclusiv automate cu efect juridic sau un efect similar semnificativ. Eligibilitatea tehnică a unui beneficiu poate fi verificată automat; o eroare poate fi contestată prin suport și analizată de o persoană.', 'Pentru limitarea probei gratuite Plus la o utilizare pe dispozitiv, aplicația trimite un hash al identificatorului Android sau al identificatorului de vendor iOS; serverul îl transformă din nou. Hashul persistent nu este considerat automat anonim doar fiindcă nu conține identificatorul brut. După ștergerea contului, asocierea cu utilizatorul este eliminată, dar marca dispozitivului poate rămâne pentru prevenirea reutilizării probei. Poți formula opoziție; necesitatea și durata acestei evidențe trebuie revizuite periodic.'] },
    { title: '7. Destinatari și transferuri', paragraphs: ['Supabase furnizează autentificarea, baza de date, funcții server și stocarea fișierelor. Furnizorul de găzduire web procesează cererile către site. Google participă la autentificare dacă o alegi și Google Cloud Vision la OCR dacă funcția este activă. Firebase poate procesa identificatorii de notificare atunci când notificările push sunt configurate și permise; unele mementouri sunt exclusiv locale. Furnizorul efectiv de e-mail tranzacțional trebuie consemnat în registrul împuterniciților la activare.', 'Nu promitem că toate datele, copiile de siguranță, metadatele și accesul furnizorilor rămân exclusiv în UE. Regiunea bazei de date nu acoperă automat toate serviciile, jurnalele și subîmputerniciții. Pentru transferuri în afara SEE trebuie verificate mecanismul aplicabil, acordurile de prelucrare și garanțiile, inclusiv clauzele contractuale standard sau o decizie de adecvare, după caz. Detaliile furnizorului și ale garanțiilor pot fi cerute la adresa de contact.', 'Localurile primesc datele necesare rezervării și vizitei autorizate. Personalul CeFaci vede numai informațiile permise rolului său. Autoritățile pot primi informații când există o obligație sau o cerere legală valabilă. Nu vindem date personale și nu acordăm acces comercial la lista de utilizatori.'] },
    { title: '8. Păstrarea și ștergerea', paragraphs: ['Datele contului și activitatea necesară serviciului se păstrează cât timp contul este activ și sunt necesare scopului lor. Ștergerea contului elimină identitatea și datele legate prin ștergere în cascadă; unele istorice de vizită, cereri și audit rămân fără asocierea directă cu contul. Eliminarea acelei asocieri nu garantează anonimizarea textului liber sau a documentelor. Aplicăm o evaluare separată pentru datele care mai identifică o persoană.', 'Accesul normal la fotografiile de suport și dovezile Business este blocat după 90 de zile. Sunt prevăzute proceduri server pentru ștergerea binarelor prin Storage și confirmarea ștergerii. Blocarea accesului nu dovedește ștergerea fizică; aceasta trebuie executată și verificată prin procedura de retenție. Nu declarăm că un scheduler rulează automat dacă nu este configurat.', 'Nu promitem ștergerea tuturor backupurilor în 30 de zile. Copiile de siguranță și jurnalele urmează ciclul documentat al furnizorului; accesul la ele este limitat, iar restaurarea trebuie să reaplice cererile de ștergere. Datele necesare unei obligații legale sau unui litigiu se păstrează separat, numai pentru perioada justificată. În prezent estimările Business nu reprezintă facturi fiscale emise de CeFaci.'] },
    { title: '9. Drepturi, plângeri și modificări', paragraphs: [rights, 'Poți depune o plângere la ANSPDCP, https://www.dataprotection.ro/?page=Plangeri_meniu, sau te poți adresa unei instanțe competente. Nu este obligatoriu să renunți la aceste drepturi pentru a utiliza suportul nostru.', 'Modificările importante ale scopurilor, temeiurilor sau destinatarilor vor fi comunicate înaintea aplicării. Un scop nou care necesită consimțământ nu este autorizat prin simpla actualizare a acestui document. Versiunea documentelor este indicată în aplicație și pe site.'] },
  ] },
  { id: 'clientTerms', title: 'Termeni de utilizare Client', path: '/termeni/', audience: ['client','website'], sections: [
    { title: '1. Serviciul și etapa proiectului', paragraphs: [operator, 'CeFaci te ajută să descoperi locuri și să organizezi ieșiri în București și Ilfov, inclusiv planuri cu prietenii, rezervări și beneficii la parteneri unde sunt active. Funcțiile și disponibilitatea sunt cele afișate efectiv. O etichetă beta nu înlătură obligațiile legale sau drepturile consumatorilor.'] },
    { title: '2. Eligibilitate și cont', paragraphs: ['Produsul este destinat persoanelor de cel puțin 16 ani. Furnizează date corecte și folosește numai contul propriu. Pentru 16–17 ani se aplică filtrele produsului; achizițiile viitoare și serviciile localului rămân supuse capacității legale și regulilor specifice acelui serviciu. Nu folosi aplicația pentru a evita restricțiile legale de vârstă.', 'Poți explora funcțiile disponibile fără cont. Funcțiile sincronizate, sociale și biletele pot necesita autentificare. Protejează codurile de acces și anunță suportul dacă suspectezi folosirea neautorizată.'] },
    { title: '3. Localuri, planuri, rezervări și beneficii', paragraphs: ['Datele despre localuri provin din surse publice, inclusiv OpenStreetMap, din verificări și din actualizările partenerilor. Programul, capacitatea și prețurile estimate se pot modifica. Confirmarea unei rezervări și condițiile unei oferte sunt cele afișate în bilet; o sugestie sau o cerere trimisă nu este o rezervare confirmată.', 'Localul răspunde pentru propriile produse, servire, reguli de acces și documente fiscale. CeFaci răspunde pentru propriile obligații privind serviciul digital. Regulile de eligibilitate, intervalul de sosire și numărul de persoane pot fi verificate de server. O reducere depinde de oferta și starea biletului, fără a restrânge drepturile legale ale clientului.', 'Poți raporta o reducere neaplicată sau o eroare prin suport. Deciziile contestate sunt verificate pe baza datelor relevante; nu oferim automat compensații financiare sau beneficii neafișate. XP-ul și ștampilele nu sunt monedă, instrument financiar ori sold convertibil în numerar.'] },
    { title: '4. Plus și plăți', paragraphs: ['Proba gratuită Plus, unde este oferită, are durata și eligibilitatea afișate în aplicație și nu se transformă automat într-o plată. Poate exista o limită de o probă pe dispozitiv. În etapa actuală nu este activat un circuit comercial complet de abonamente și facturare.', 'Nu se încheie prin acești termeni un abonament cu reînnoire automată și nu promitem că plata prin Google Play ori App Store este disponibilă. Înaintea unei viitoare achiziții trebuie afișate operatorul comercial, prețul total, taxele, durata, reînnoirea, anularea, condițiile de retragere și modalitatea de reclamație. Acceptarea acestor termeni nu reprezintă o renunțare la retragere sau la garanțiile legale.'] },
    { title: '5. Utilizare corectă și conținut', paragraphs: ['Nu impersona alte persoane, nu hărțui, nu publica datele altora fără drept, nu trimite conținut ilegal ori cod executabil și nu reutiliza bonuri, bilete sau conturi pentru beneficii neeligibile. Nu încerca să ocolești autorizarea, limitele sau controalele de securitate. Testarea unei vulnerabilități trebuie să se oprească înainte de accesul la datele altei persoane.', 'Poți transmite numai imagini și documente pentru care ai dreptul să le folosești. Ne permiți prelucrarea și afișarea lor strict pentru funcția cerută, suport și verificare, fără transferul proprietății tale intelectuale. Raportează conținutul ilegal ori încălcarea unui drept, indicând elementul afectat și motivul.'] },
    { title: '6. Suspendare, ștergere și contestație', paragraphs: [`Putem limita accesul proporțional în caz de abuz, risc de securitate sau obligație legală. Comunicăm motivul și o cale de contestare când legea permite; o urgență de securitate poate necesita blocarea imediată. Poți cere o reevaluare la ${email}. Nu aplicăm o excludere arbitrară de la drepturile legale.`, 'Poți înceta folosirea și solicita ștergerea contului din aplicație sau prin pagina Șterge contul. Ștergerea contului nu înlocuiește o eventuală anulare separată a unei rezervări și nu șterge obligațiile legale valabile. Politica de confidențialitate explică istoricele, retenția și backupurile.'] },
    { title: '7. Disponibilitate, răspundere și litigii', paragraphs: ['Lucrăm la remedierea erorilor și la păstrarea funcțiilor sigure, dar pot exista întreruperi sau informații externe neactualizate. Nu garantăm că orice local este deschis ori că orice ofertă este disponibilă. Aceste precizări nu exclud răspunderea care nu poate fi limitată legal, inclusiv pentru intenție, culpă gravă sau încălcarea drepturilor obligatorii ale consumatorului.', `Pentru reclamații scrie la ${email}; suportul intern nu împiedică sesizarea ANPC, ANSPDCP sau a unei instanțe competente. Pentru litigii de consum poți consulta procedura SAL la https://anpc.ro/ce-este-sal/. Platforma europeană SOL/ODR a fost închisă la 20 iulie 2025 și nu este prezentată ca serviciu activ.`, 'Se aplică legea română, cu respectarea protecțiilor obligatorii aplicabile consumatorului. Nu impunem unui consumator competența exclusivă a unei instanțe dintr-un oraș ales de noi. Modificările importante se anunță în prealabil și nu afectează retroactiv drepturile dobândite.'] },
  ] },
  { id: 'cookies', title: 'Cookies și stocarea pe dispozitiv', path: '/cookies/', audience: ['client','business','admin','website'], sections: [
    { title: '1. Ce acoperă politica', paragraphs: ['Această politică privește cookie-uri, localStorage, sessionStorage și stocarea locală a aplicațiilor. O cheie de stocare locală nu este automat un cookie, dar poate intra sub regulile accesului la echipamentul terminal. Folosim în versiunea actuală numai stocări pentru funcțiile cerute, securitate și preferințe ale interfeței; nu includem pixeli de marketing, SDK-uri publicitare sau analiză comportamentală.', 'Stocarea strict necesară furnizării serviciului cerut poate beneficia de excepția prevăzută de art. 4 alin. (6) din Legea 506/2004. Această excepție nu acoperă automat orice scop util operatorului. O viitoare statistică facultativă sau publicitate va necesita evaluarea temeiului și, când este cazul, consimțământ prealabil, specific și retractabil.'] },
    { title: '2. Site-ul cefaci.app', paragraphs: ['Fonturile și imaginile sunt găzduite împreună cu site-ul. Linkurile spre aplicații și e-mail nu încarcă în prealabil conținut de tracking al unui furnizor extern. Serverul de găzduire poate avea jurnale HTTP; acestea nu sunt cookie-uri și sunt descrise în politica de confidențialitate.', 'Site-ul folosește cheia localStorage cefaci.site.theme numai când alegi explicit tema de zi sau de noapte. Până atunci folosește preferința sistemului fără a o scrie în stocare. Controlul Setări stocare permite ștergerea acestei chei și revenirea la tema sistemului. Preferința rămâne până când o ștergi sau cureți datele site-ului. Nu există cookies de marketing, analytics sau un buton fictiv de acceptare a acestora.'] },
    { title: '3. Client', paragraphs: ['Cheile cefaci.prefs și cefaci.state păstrează preferințele și progresul; cefaci.onboarded și cefaci.owner susțin reluarea și separarea stării conturilor. Cache-ul de localuri și cheile cefaci.planAsk și ale sugestiilor recente susțin catalogul și formularul cerut. Ele rămân până la resetarea aplicației, ștergerea datelor ori înlocuirea lor de fluxul aplicației; anumite sugestii recente sunt filtrate la două zile.', 'Sesiunea Supabase folosește chei de tip sb-<proiect>-auth-token în stocarea aplicației Client; durata sesiunii și reînnoirea sunt controlate de autentificare. Nu susținem că tokenul Client este un cookie HttpOnly. Ștergerea datelor locale poate deconecta contul și poate pierde progresul nesincronizat. Hashul dispozitivului folosit pentru limitarea probei Plus este explicat în informarea de confidențialitate și necesită o evaluare separată a proporționalității și a regulilor privind terminalul.'] },
    { title: '4. Business și Admin', paragraphs: ['În Business web și Admin, tokenul de autentificare se păstrează în sessionStorage pe durata tabului. Logoutul și revocarea sunt verificate de server. Sesiunea privilegiată are limite suplimentare: Admin 15 minute de inactivitate și maximum 8 ore, Business 30 de minute și maximum 12 ore; după expirare se cere o verificare MFA nouă.', 'Business nativ păstrează sesiunea prin Expo SecureStore, în stocarea securizată a sistemului de operare. business-theme păstrează tema, iar marcajele tutorialului indică dacă turul a fost parcurs pentru cont, rol și local. Admin folosește cefaci-admin-theme și marcaje de tutorial de tip cefaci.tour. Aceste preferințe nu sunt folosite pentru publicitate. Unele chei pot avea prefixe sau sufixe generate pentru cont și versiune.'] },
    { title: '5. Control și modificări', paragraphs: [`Poți șterge stocarea din setările browserului/dispozitivului, te poți deconecta sau poți reseta aplicația. Refuzul permisiunilor de locație, cameră sau notificări se gestionează separat din sistemul de operare. Pentru întrebări: ${email}.`, 'Dacă adăugăm servicii facultative, publicăm numele, scopul, furnizorul și durata lor înainte de activare. Refuzul și retragerea trebuie să fie la fel de ușoare ca acceptarea și să oprească viitoarele accesări facultative; acceptarea politicii de confidențialitate nu este consimțământ pentru tracking.'] },
  ] },
  { id: 'businessTerms', title: 'Reguli și termeni Business beta', path: '/business/termeni/', audience: ['business','website'], sections: [
    { title: '1. Cine oferă dashboardul', paragraphs: [operator, 'Acești termeni acoperă accesul de test și utilizarea funcțiilor Business disponibile. Nu țin locul unui contract comercial de parteneriat, al unui acord de împuternicire sau al unei facturi. Condițiile comerciale și operatorul fiscal trebuie confirmate separat înaintea activării comerciale.'] },
    { title: '2. Solicitarea și dreptul asupra unui local', paragraphs: ['Poți revendica un local existent, solicita adăugarea unui local sau contesta o asociere incorectă. Furnizează datele reale ale firmei și dovada dreptului de reprezentare; evită documentele cu date personale nerelevante. O cerere depusă sau verificată nu acordă automat proprietatea localului, drepturi administrative ori contract activ.', 'Verificarea firmei, a reprezentării și a conflictelor se face prin fluxul autorizat. Activarea partenerului și atribuirea rolului sunt etape distincte. Nu adăuga oferte sau nu acționa pentru un local fără mandat.'] },
    { title: '3. Cont individual, roluri și MFA', paragraphs: ['Accesul operațional este individual și necesită autentificare multifactor. Rolurile owner, manager, recepție și scanare au permisiuni diferite și sunt limitate la localul autorizat. Contul solicitantului poate vedea propriile cereri înaintea activării, fără acces la operațiunile localului.', 'Nu distribui contul, codurile MFA sau sesiunea. Administratorul localului trebuie să acorde numai drepturile necesare și să retragă accesul când colaborarea încetează. Raportează imediat compromiterea. Serverul poate închide o sesiune ori refuza o operațiune după revocarea rolului chiar dacă interfața era deja deschisă.'] },
    { title: '4. Rezervări, vizite, oferte și reclamații', paragraphs: ['Menține actuale capacitatea, programul și condițiile ofertelor. Confirmările, propunerile, anulările, scanările și disputele trebuie să reflecte situația reală. Nu crea vizite, bonuri sau reduceri fictive pentru statistici ori comisioane. Aplică oferta confirmată în condițiile biletului și explică un refuz justificat.', 'Localul răspunde pentru autorizările proprii, informarea consumatorilor, limitele de vârstă, siguranța serviciului, documentele fiscale și încasarea de la client. Fluxul CeFaci nu înlocuiește casa de marcat, bonul fiscal sau obligațiile localului.', 'La o dispută, răspunde în intervalul afișat și trimite numai dovezile relevante. Admin poate analiza și decide în limitele drepturilor sale; o decizie internă nu înlătură căile legale de reclamație.'] },
    { title: '5. Date personale și confidențialitate', paragraphs: ['Folosește datele clienților numai pentru rezervarea, vizita și cererea relevante. Nu exporta liste pentru marketing, nu contacta clienții în afara scopului declarat și nu publica bilete, bonuri sau capturi cu date personale. Accesul tehnic nu constituie acordul clientului pentru comunicări comerciale.', 'Părțile trebuie să documenteze dacă sunt operatori independenți sau dacă, pentru o operațiune concretă, CeFaci acționează ca împuternicit. Un acord GDPR art. 28 se semnează când rolul real îl cere; nu pretindem că există deja un DPA semnat pentru toți partenerii.', `Transmite imediat suspiciunile de incident la ${email}, fără coduri de acces în e-mail. Ajută la cererile persoanelor vizate și la ștergerea datelor din propriile exporturi, când aceasta este legal necesară.`] },
    { title: '6. Estimări și circuit fiscal', paragraphs: ['Valorile din Plăți/Financiar sunt estimări și pot fi parțiale dacă lipsesc bonuri ori există dispute. Circuitul de facturare al platformei rămâne dezactivat, billing_ready=false. Afișarea unui comision estimat nu emite o factură, nu transmite e-Factura și nu autorizează debitarea unui cont.', 'Înainte de activarea comercială sunt necesare identitatea fiscală a operatorului, contractul cu preț/bază de calcul/TVA/scadență, procedura de corecție, emitentul documentelor, accesul SPV și integrarea RO e-Factura aplicabilă. Nu este activată prin acești termeni autofacturarea și nu înlocuim validarea unui contabil.'] },
    { title: '7. Suspendare, încetare și modificări', paragraphs: [`Putem limita accesul pentru fraudă, revendicare contestată, risc de securitate sau încălcare a regulilor, proporțional cu situația. Poți contesta la ${email}. Închiderea unui cont de angajat nu transferă automat proprietatea localului și nu șterge datele obligatorii ale firmei.`, 'Contractul comercial viitor va preciza răspunderea, durata, încetarea și mecanismele de soluționare a disputelor. Acest document beta nu inventează aceste condiții și nu limitează obligațiile legale existente. Actualizările importante ale regulilor se comunică înaintea aplicării.'] },
  ] },
  { id: 'adminRules', title: 'Reguli Admin și confidențialitate', path: '/admin/reguli/', audience: ['admin','website'], sections: [
    { title: '1. Acces profesional autorizat', paragraphs: ['Admin este destinat exclusiv persoanelor autorizate individual de operatorul CeFaci. Nu este un serviciu de înscriere publică. Rolul fondator nu permite ignorarea regulilor privind datele, auditul sau obligațiile legale. Aceeași politică de confidențialitate a platformei se aplică datelor personalului și utilizatorilor.', 'Folosește contul propriu și MFA; nu transmite secrete TOTP, coduri de verificare, tokenuri sau copii ale unei sesiuni. După expirare sau revocare nu încerca să redeschizi accesul prin ocolirea serverului.'] },
    { title: '2. Roluri și scop', paragraphs: ['Rolurile fondator, admin, editor, moderator, suport și contabil au accesul configurat pe server. Interfața și turul Bilu explică funcțiile disponibile rolului curent; tutorialul nu acordă permisiuni. Consultă o cerere sau un cont numai dacă este necesar unei sarcini atribuite.', 'Folosește numai permisiunile necesare cazului. Personalul care lucrează la comunicarea proiectului nu primește prin acest document un drept de folosire a datelor pentru campanii. Schimbările de rol, suspendările, verificările de parteneri și deciziile financiare trebuie să aibă un motiv real și verificabil.'] },
    { title: '3. Date, documente și jurnal', paragraphs: ['Nu descărca sau copia date în conturi personale, aplicații AI, mesagerii ori clouduri neaprobate. Nu trimite documente de reprezentare sau imagini de suport în afara fluxului autorizat. Evită capturile; dacă sunt indispensabile unei investigații, minimizează datele, limitează accesul și șterge-le la încheiere conform retenției aprobate.', 'Jurnalul acțiunilor urmărește siguranța și justificarea deciziilor. Nu altera probele, nu șterge un caz pentru a ascunde o eroare și nu face investigații din curiozitate. Corectează prin mecanismul permis și păstrează explicația necesară. Accesul temporar la un atașament privat nu autorizează redistribuirea lui.'] },
    { title: '4. Cereri GDPR și incidente', paragraphs: [`Cererile privind datele trebuie înregistrate și transmise responsabilului desemnat la ${email}. Nu confirma identitatea prin cererea unor acte excesive și nu promite ștergerea backupurilor ori a evidențelor fiscale fără verificarea scopului și obligației legale.`, 'Anunță imediat o accesare suspectă, un fișier expus, un e-mail trimis greșit sau pierderea unui dispozitiv. Nu aștepta finalizarea propriei investigații. Operatorul evaluează notificarea ANSPDCP în cel mult 72 de ore de la luarea la cunoștință, când încălcarea prezintă risc; nu orice eroare de interfață este o încălcare de date.'] },
    { title: '5. Încetare și responsabilitate', paragraphs: ['La încetarea sarcinii sau colaborării, accesul se revocă, sesiunile se închid și copiile de lucru sunt returnate ori șterse conform instrucțiunilor legale. Obligația de confidențialitate continuă pentru informațiile care rămân protejate.', 'Aceste reguli sunt instrucțiuni operative; nu înlocuiesc contractul de muncă/colaborare, angajamentul de confidențialitate ori acordul cu un împuternicit extern. Operatorul trebuie să documenteze mandatul, instruirea și responsabilitățile fiecărei persoane.'] },
  ] },
  { id: 'rights', title: 'Datele tale și drepturile GDPR', path: '/drepturile-tale/', audience: ['client','business','admin','website'], sections: [
    { title: '1. Cum trimiți o cerere', paragraphs: [`Scrie la ${email}, de preferință de pe e-mailul contului, cu tipul cererii și aplicația folosită: Client, Business sau Admin. Poți cere acces/export, corectare, ștergere, restricționare ori formula opoziție. Nu trimite parola, codul OTP, cheia MFA, CNP sau un act de identitate în primul mesaj.`, 'Pentru acces și portabilitate, indică dacă dorești toate datele proprii sau o categorie anume. Cererile sunt în principiu gratuite. Dacă identitatea este neclară, cerem numai informațiile suplimentare necesare verificării, fără a solicita automat o copie de document.'] },
    { title: '2. Termen și soluționare', paragraphs: [rights, 'Din Datele mele poți trimite o cerere cu un număr de caz și poți urmări răspunsul în cont, inclusiv înainte de deschiderea unui dashboard Business/Admin prin MFA. Nu confunda un raport de problemă obișnuit cu o cerere de drepturi: indică explicit că dorești exercitarea unui drept GDPR. Dacă refuzăm integral sau parțial, explicăm motivul, temeiul și calea de reclamație.', 'Exportul rapid din aplicație conține profilul, preferințele de bază și până la 100 de cereri privind datele, cu indicarea unei eventuale trunchieri. Nu este un export complet al tuturor planurilor, mesajelor, rezervărilor, jurnalelor și atașamentelor și nu înlocuiește răspunsul integral la o cerere de acces sau portabilitate. Pentru categoriile suplimentare trimite o cerere formală.'] },
    { title: '3. Limite și alegeri', paragraphs: ['Portabilitatea se aplică datelor prelucrate automat, în baza consimțământului sau contractului, în condițiile GDPR. Dreptul de opoziție privește în special interesul legitim; cererea este analizată în raport cu motivul invocat. Ștergerea poate avea excepții pentru obligații legale și apărarea drepturilor, cu minimizare și acces limitat.', 'Retragerea unei permisiuni din telefon oprește viitoarele accesări prin acea permisiune, dar nu este automat o cerere de ștergere a datelor deja trimise. Eliminarea aplicației nu șterge automat contul. Poți folosi pagina Șterge contul sau contactul de mai sus.'] },
    { title: '4. Autoritatea de supraveghere', paragraphs: ['Poți depune plângere la ANSPDCP: https://www.dataprotection.ro/?page=Plangeri_meniu. Păstrează cererea, răspunsurile și datele relevante. Ai și dreptul la o cale judiciară; nu este necesar să accepți soluția suportului.'] },
  ] },
  { id: 'security', title: 'Securitate și raportarea vulnerabilităților', path: '/securitate/', audience: ['client','business','admin','website'], sections: [
    { title: '1. Cum protejăm accesul', paragraphs: ['Business și Admin folosesc MFA obligatoriu pentru operațiuni, permisiuni verificate pe server și sesiuni privilegiate care expiră. Rolurile și accesul la un local sunt separate. Fișierele de suport și dovezile de reprezentare sunt private și necesită autorizare temporară.', 'Business nativ folosește stocarea securizată a sistemului de operare pentru sesiune; dashboardurile web păstrează sesiunea în tab. Aceste măsuri reduc riscul și nu reprezintă o garanție de invulnerabilitate, o certificare sau o promisiune că orice dispozitiv compromis rămâne sigur.'] },
    { title: '2. O problemă obișnuită', paragraphs: ['Folosește Raportează problema din profilul Client sau secțiunea Business. Adaugă un titlu, descriere și o poză opțională, cu datele altor persoane mascate. Nu include parole, OTP, chei MFA ori date de card. Raportul ajunge la echipa autorizată în Admin.'] },
    { title: '3. O vulnerabilitate de securitate', paragraphs: [`Trimite la ${email} cu subiectul Securitate CeFaci. Descrie componenta, pașii minimi de reproducere, impactul presupus și ora observației. Folosește propriul cont și date de test. Nu atașa baze de date, tokenuri active sau documentele altor persoane.`, 'Nu continua accesul după demonstrarea minimă a problemei. Nu încerca parolele altor persoane, nu modifica datele lor, nu provoca indisponibilitate și nu publica date personale. Această pagină nu autorizează atacuri sau teste intruzive și nu instituie automat un program de recompense. Raportarea responsabilă va fi analizată prin canalul de contact.'] },
    { title: '4. Dacă suspectezi compromiterea contului', paragraphs: ['Deconectează-te de pe dispozitivele pe care le controlezi, securizează e-mailul și contactează suportul. Dacă ai un rol Business/Admin, cere revocarea accesului sau a sesiunii afectate. Nu comunica factorul TOTP unui presupus membru al echipei: suportul nu are nevoie de secretul tău MFA.'] },
  ] },
  { id: 'contact', title: 'Contact și informații despre proiect', path: '/contact/', audience: ['client','business','admin','website'], sections: [
    { title: '1. Contact direct', paragraphs: [operator, `Pentru suport, reclamații, drepturi GDPR, localuri lipsă și securitate: ${email}. Specifică aplicația și subiectul, fără secrete sau date personale inutile. Cererile din aplicație sunt analizate prin dashboardul Admin de rolurile autorizate.`] },
    { title: '2. Stadiu și informații comerciale', paragraphs: ['CeFaci se află în dezvoltare și testare. În prezent nu există o firmă CeFaci înregistrată, iar circuitul comercial de facturare este dezactivat. Nu publicăm un CUI, sediu social ori număr de registru inventat.', 'Înaintea lansării comerciale trebuie completate identitatea verificată a furnizorului, adresa și datele de contact efectiv, înregistrarea fiscală și registrul aplicabil, precum și informațiile despre preț, TVA, contract și reclamații. Această pagină nu afirmă că formalitățile comerciale sunt deja îndeplinite.'] },
    { title: '3. Reclamații și autorități', paragraphs: ['Reclamațiile privind propriul serviciu CeFaci se trimit la contactul de mai sus. Pentru serviciul unui local, contactează și localul care îl furnizează. Poți consulta ANPC și procedura SAL: https://anpc.ro/ce-este-sal/. Pentru date personale: https://www.dataprotection.ro/?page=Plangeri_meniu.', 'Platforma SOL/ODR a Comisiei Europene a fost închisă la 20 iulie 2025. Nu te trimitem la ea pentru o reclamație nouă. Contactarea noastră nu limitează dreptul de a sesiza autoritățile sau instanțele competente.'] },
  ] },
  { id: 'deleteAccount', title: 'Șterge contul CeFaci', path: '/sterge-contul/', audience: ['client','business','admin','website'], sections: [
    { title: '1. Din aplicația Client', paragraphs: ['Deschide Profil și folosește butonul Șterge-mi contul din partea de jos, apoi confirmă alegerea. Ai nevoie de internet pentru ștergerea contului de pe server. Dacă serverul nu confirmă operațiunea, aplicația arată eroarea și trebuie să reîncerci; simpla ștergere a datelor locale nu este o confirmare de ștergere a contului.', 'Ștergerea imediată este disponibilă numai când contul nu are operațiuni sau documente care cer verificare. Un rol Business/Admin, rezervări, Drop-uri, vizite, bonuri, documente private sau cereri de drepturi încă deschise pot trimite cazul către analiza manuală. În acest caz primești o explicație și poți solicita ștergerea din Datele mele sau prin e-mail; nu afirmăm că ștergerea a reușit.', 'După confirmarea ștergerii, accesul și profilul sunt eliminate, inclusiv legăturile șterse în cascadă. Poți pierde prietenii, progresul și planurile asociate. Verifică separat anularea rezervărilor active și obligațiile care pot exista față de local.'] },
    { title: '2. Fără acces la aplicație sau pentru Business/Admin', paragraphs: [`Trimite la ${email} cu subiectul Ștergere cont CeFaci, de pe adresa asociată contului dacă este posibil. Indică aplicația și username-ul, fără parolă, cod OTP, secret MFA ori acte în primul mesaj. Dacă nu mai ai acces la e-mail, explică acest lucru pentru o verificare proporțională.`, 'La un cont Business, clarificăm și drepturile echipei, reprezentarea localului și eventualul transfer autorizat al rolului de owner. Ștergerea contului tău nu transferă automat localul și nu șterge datele proprii ale firmei. La Admin, revocarea accesului operațional se face imediat separat de analiza evidențelor care trebuie păstrate.'] },
    { title: '3. Ce poate rămâne', paragraphs: ['Unele istorice de vizite, cereri de suport și jurnale păstrează evenimentul fără legătura directă cu contul. Textul liber și atașamentele pot necesita ștergere sau redactare separată. Dovezile și pozele au limita de acces de 90 de zile și o procedură de ștergere fizică, descrise în politica de confidențialitate.', 'Marca pseudonimizată a dispozitivului pentru limitarea probei Plus poate rămâne fără asocierea cu contul. Backupurile și jurnalele urmează ciclurile furnizorului, nu o promisiune de ștergere totală în 30 de zile. Pentru o obligație legală ori un litigiu păstrăm numai datele necesare și explicăm o excepție aplicabilă cererii tale.'] },
    { title: '4. Confirmare și drepturi', paragraphs: [rights, 'Dezinstalarea aplicației, închiderea tabului sau logoutul nu șterg automat contul. Cererea prin e-mail rămâne disponibilă chiar dacă nu mai poți intra în aplicație.'] },
  ] },
];
export function getLegalDocument(id: string): LegalDocument | undefined { return LEGAL_DOCUMENTS.find(document => document.id === id); }
