/** Guidance only. Access is always checked by the API, never by tutorial progress. */
export const TUTORIAL_VERSION = 1;
export type AdminTourTab = 'home'|'requests'|'reports'|'places'|'partners'|'operations'|'finance'|'plus'|'suggestions'|'people'|'staff'|'journal';
export type TutorialStep = {id:string;title:string;text:string;tip?:string;tab?:string;action?:string};
export const adminRoleLabels:Record<string,string> = {fondator:'fondator',admin:'administrator',editor:'editor',moderator:'moderator',suport:'suport',contabil:'contabil'};
export const businessRoleLabels:Record<string,string> = {proprietar:'proprietar',manager:'manager',receptie:'recepție',scanare:'scanare',applicant:'solicitant'};
type AdminEntry = TutorialStep & {permission?:string};
const adminSteps:AdminEntry[] = [
 {id:'overview',tab:'home',title:'Totul începe de aici.',text:'Pe Acasă vezi cifrele și listele disponibile rolului tău. Deschide o listă ca să ajungi direct la ce ai de rezolvat.',action:'Deschide Acasă'},
 {id:'requests',tab:'requests',permission:'partners',title:'Cine stă în spatele localului?',text:'În Cereri Business verifici solicitantul, localul și dovada. Citește și răspunsul proprietarului existent înainte să decizi.',tip:'Verificarea cererii nu activează automat parteneriatul sau dreptul de proprietar.',action:'Deschide cererile'},
 {id:'reports',tab:'reports',permission:'reports.read',title:'Un răspuns care chiar ajută.',text:'Semnalările reunesc problemele și localurile lipsă din Client și Business. Citește descrierea și poza privată, apoi verifică istoricul.',tip:'Răspunde clar cu ce ai verificat și ce urmează. Acțiunile disponibile depind de permisiunile tale.',action:'Deschide semnalările'},
 {id:'places',tab:'places',permission:'staff.read',title:'Catalogul pe care îl văd oamenii.',text:'Caută localul în Locuri și verifică informațiile existente. Dacă ai drept de editare, schimbă numai ce ai confirmat.',tip:'Localurile ascunse rămân în catalogul Admin pentru verificare.',action:'Deschide localurile'},
 {id:'operations',tab:'operations',permission:'operations.read',title:'Aceeași ieșire, același context.',text:'În Sosiri găsești vizitele, rezervările și cazurile care cer atenție. Verifică numărul de persoane, starea beneficiului și istoricul înainte de orice decizie.',tip:'Dacă rolul permite decizii, acestea rămân în jurnal. Simplul acces la listă nu înseamnă drept de modificare.',action:'Deschide sosirile'},
 {id:'partners',tab:'partners',permission:'partners.read',title:'Partenerii, fără presupuneri.',text:'În Parteneri vezi starea reală a colaborării și echipa localului. Folosește datele confirmate, nu promisiunile dintr-o cerere.',action:'Deschide partenerii'},
 {id:'finance',tab:'finance',permission:'money.read',title:'Cifrele au nevoie de context.',text:'În Bani alegi perioada și verifici încasările, reducerile și taxele eligibile separat. Cazurile blocate sau incomplete trebuie lămurite.',tip:'Sumele sunt estimări. Emiterea facturilor și încasarea plăților nu sunt configurate.',action:'Deschide situația financiară'},
 {id:'people',tab:'people',permission:'users.read',title:'Găsește contul potrivit.',text:'În Oameni cauți numele de utilizator exact. Verifică identitatea contului înainte să legi o solicitare sau o intervenție de el.',tip:'Nu ai nevoie de emailul, data nașterii sau alte date personale pentru acest pas.',action:'Deschide Oameni'},
 {id:'plus',tab:'plus',permission:'plus.manage',title:'Un gest mic, cu un motiv clar.',text:'În Plus poți acorda compensarea disponibilă unui cont eligibil. Verifică utilizatorul, explică motivul și confirmă numai cazul verificat.',tip:'Serverul aplică limitele. Turul nu acordă Plus și nu modifică niciun cont.',action:'Deschide Plus'},
 {id:'suggestions',tab:'suggestions',permission:'suggestions.read',title:'Date reale pentru următorul partener.',text:'Sugestiile pornesc de la check-in-uri și bonuri înregistrate. Folosește-le ca punct de pornire pentru verificarea unui local.',tip:'Activitatea observată nu dovedește proprietatea și nu activează un parteneriat.',action:'Deschide sugestiile'},
 {id:'team',tab:'staff',permission:'staff.read',title:'Fiecare om, cu rolul potrivit.',text:'În Echipa verifici rolurile active. Dacă ai drept de administrare, acordă doar accesul necesar și notează motivul schimbării.',tip:'Nu împărți conturi, parole, coduri de autentificare sau coduri de recuperare.',action:'Deschide echipa'},
 {id:'audit',tab:'journal',permission:'audit.read',title:'Deciziile lasă urme.',text:'Jurnalul te ajută să vezi cine a schimbat ceva, când și de ce. Folosește istoricul pentru verificări și rezolvarea neînțelegerilor.',action:'Deschide jurnalul'},
];
export function adminTutorial(role:string,permissions:readonly string[],availableTabs?:readonly string[]):TutorialStep[] {
 if (!Object.prototype.hasOwnProperty.call(adminRoleLabels,role)) return [];
 const allowed=adminSteps.filter(s=>(!s.permission||permissions.includes(s.permission))&&(!availableTabs||!s.tab||availableTabs.includes(s.tab)));
 return [{id:'welcome',title:'Salut! Bilu la datorie.',text:`Îți arăt Adminul pentru rolul de ${adminRoleLabels[role]}. Un tur scurt, prin ecranele la care ai acces.`,tip:'Folosim paginile reale. Turul nu trimite răspunsuri și nu schimbă date.'},...allowed.map(({permission:_,...step})=>step),{id:'finish',title:'Gata. Acum știi pe unde mergi.',text:'Ai un caz concret? Începe din lista potrivită și verifică întâi contextul.',tip:'Poți relua turul oricând. Pe un dispozitiv comun, ieși din cont când ai terminat.'}];
}
const businessSteps:TutorialStep[] = [
 {id:'today',tab:'Azi',title:'Bună seara începe cu Azi.',text:'Vezi sosirile și starea serii pentru localul selectat. Deschide vizita potrivită și verifică persoanele înainte de a schimba ceva.',action:'Deschide Azi'},
 {id:'reservations',tab:'Rezervări',title:'Rezervări care ajung la client.',text:'Aici vezi cererile reale. Confirmă, refuză sau propune altă oră numai după ce ai verificat disponibilitatea.',tip:'Răspunsul tău ajunge în Client. Confirmările sunt verificate de server; offline nu poți confirma capacitatea.',action:'Deschide rezervările'},
 {id:'scanner',tab:'Scanner',title:'Scanezi. Verifici. Confirmi.',text:'Scanează biletul grupului și citește rezultatul serverului. O scanare repetată a aceleiași ieșiri nu trebuie să creeze o sosire nouă.',tip:'Nu confunda afișarea codului cu o sosire confirmată. Verifică rezultatul și numărul de persoane.',action:'Deschide scannerul'},
 {id:'offers',tab:'Oferte',title:'O ofertă clară pentru toată lumea.',text:'Verifică reducerile și ofertele localului înainte să le modifici. Folosește procentele și intervalele reale.',tip:'Schimbările programului și reducerii se aplică după regulile afișate. Drepturile vizitelor existente se păstrează.',action:'Deschide ofertele'},
 {id:'finance',tab:'Financiar',title:'Sumele, fiecare la locul ei.',text:'Alege perioada și verifică încasările totale, reducerile și taxele eligibile separat. Cazurile incomplete au nevoie de verificare.',tip:'Facturarea și plățile nu sunt configurate. CeFaci nu calculează profitul restaurantului.',action:'Deschide Financiar'},
 {id:'statistics',tab:'Statistici',title:'Vezi ce s-a întâmplat cu adevărat.',text:'Compară activitatea înregistrată pentru localul selectat. Ține cont de perioadă și de stările vizitelor.',action:'Deschide statisticile'},
 {id:'profile',tab:'Profil',title:'Localul tău, cu informații corecte.',text:'Verifică profilul, programul și datele localului. Actualizează numai informațiile confirmate și urmărește mesajul de salvare.',action:'Deschide profilul'},
 {id:'team',tab:'Echipă',title:'Fiecare coleg are contul lui.',text:'Verifică cine are acces la local și ce rol are. Acordă fiecărui coleg doar responsabilitățile de care are nevoie.',tip:'Nu împărți contul proprietarului și nu trimite coduri de autentificare colegilor.',action:'Deschide echipa'},
 {id:'help',tab:'Ajutor',title:'Ai găsit o problemă? Spune-ne.',text:'În Ajutor trimiți un titlu, o descriere și, dacă ajută, o poză. Urmărește aici starea și răspunsul echipei CeFaci.',tip:'Nu include parole, coduri de autentificare sau date inutile despre clienți în raportare.',action:'Deschide Ajutor'},
];
const businessAllowed:Record<string,readonly string[]>={proprietar:['Azi','Rezervări','Scanner','Oferte','Financiar','Statistici','Profil','Echipă','Ajutor'],manager:['Azi','Rezervări','Scanner','Oferte','Financiar','Statistici','Profil','Echipă','Ajutor'],receptie:['Azi','Rezervări','Scanner','Ajutor'],scanare:['Azi','Scanner','Ajutor']};
export function businessTutorial(role:string,availableTabs:readonly string[]):TutorialStep[] {
 if(role==='applicant')return [{id:'welcome',title:'Hai să-ți găsim localul.',text:'Ai deja cont CeFaci? Folosește-l și în Business. Nu trebuie să faci un cont separat.',tip:'Accesul la un local apare numai după verificarea cererii sau invitației.'},{id:'claim',tab:'Cereri',title:'Caută. Revendică. Așteaptă verificarea.',text:'Caută localul și trimite cererea cu dovada potrivită. Dacă nu îl găsești, solicită adăugarea lui.',tip:'Trimiterea cererii nu te face automat proprietar.',action:'Deschide cererile'},{id:'help',tab:'Ajutor',title:'Bilu știe unde ceri ajutor.',text:'Dacă ceva nu merge, trimite problema din Ajutor. Vezi acolo starea raportării și răspunsul echipei.',action:'Deschide Ajutor'},{id:'finish',title:'De aici urmărim cererea.',text:'Verifică răspunsul în Business. După ce ai acces la local, primești turul pentru rolul tău.'}].filter(s=>!s.tab||availableTabs.includes(s.tab));
 const allowed=Object.prototype.hasOwnProperty.call(businessAllowed,role)?businessAllowed[role]:undefined;if(!allowed)return [];
 return [{id:'welcome',title:'Salut! Sunt Bilu, colegul de tur.',text:`Îți arăt Business pentru rolul de ${businessRoleLabels[role]}, la localul selectat.`,tip:'Turul deschide ecranele reale, fără să confirme rezervări, scanări sau schimbări.'},...businessSteps.filter(s=>!!s.tab&&allowed.includes(s.tab)&&availableTabs.includes(s.tab)),{id:'finish',title:'Ești gata de treabă.',text:'Verifică mereu localul selectat și rezultatul operațiunii. Dacă ai mai multe localuri, accesul poate fi diferit la fiecare.',tip:'Reiei turul oricând din meniu. Pe un dispozitiv comun, ieși din cont la final.'}];
}
/** Storage contains a completion marker only, never session tokens or business data. */
export function tutorialKey(app:'admin'|'business',userId:string,role:string,venueId='') {
 return ['cefaci',app,'tutorial',String(TUTORIAL_VERSION),userId,role,venueId].map(encodeURIComponent).join(':');
}
export const TUTORIAL_DONE='done';
