import asyncio
from playwright.async_api import async_playwright
async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch(); pg = await b.new_page(viewport={'width': 390, 'height': 844})
        errs=[]; pg.on('pageerror', lambda e: errs.append(str(e)))
        await pg.goto('file:///home/claude/cefaci-app/dist/index.html'); await pg.wait_for_timeout(800)
        async def tap(t, wait=350):
            await pg.click(t); await pg.wait_for_timeout(wait)
        await tap('text=Continuă cu telefonul')
        await pg.fill('#ph', '722123456'); await pg.wait_for_timeout(200)
        await tap('text=Trimite-mi codul', 900)
        await tap('text=Scrie codul', 600)
        btns = await pg.locator('button.big').all_inner_texts(); print('big', btns)
        await tap('button.big', 700)
        await pg.fill('#fn', 'Cornel'); await pg.fill('#un', 'cornel.test'); await pg.wait_for_timeout(200)

        await tap('button:has-text("2001")')
        await pg.screenshot(path='shots/k2.png')
        await tap('button.big', 600)
        await tap('button:has-text("Sector 2")')
        await pg.screenshot(path='shots/k3.png')
        await tap('button.big', 600)
        for t in ['Mâncare bună', 'Club și party', 'Bowling și jocuri']: await tap(f'button:has-text("{t}")', 150)
        await tap('button.big', 600); await tap('button.big', 800)
        await pg.screenshot(path='shots/k4.png')
        for i in range(5): await tap('button:has-text("Da!")', 500)
        await pg.wait_for_timeout(600)
        await pg.screenshot(path='shots/k5.png')
        big = pg.locator('button.big'); 
        if await big.count(): await tap('button.big', 600)
        await pg.screenshot(path='shots/k6.png')
        await tap('button.big', 800)
        await pg.screenshot(path='shots/k7.png')
        await tap('text=Intră în aplicație', 2500)
        await pg.screenshot(path='shots/d1.png')
        await tap('text=Sari peste', 800)
        await pg.screenshot(path='shots/d2.png')
        await tap('button.tab:has-text("Explorează")', 1200)
        await pg.screenshot(path='shots/d3.png')
        await pg.fill('#sq', 'caru cu bere'); await pg.wait_for_timeout(700)
        await pg.screenshot(path='shots/d4.png')
        await pg.fill('#sq', ''); await pg.wait_for_timeout(500)
        await pg.locator('article.card').first.locator('button').last.click(); await pg.wait_for_timeout(3500)
        await pg.screenshot(path='shots/d5.png')
        await pg.screenshot(path='shots/d6.png'); await pg.locator('button[aria-label="Închide"]').first.click(); await pg.wait_for_timeout(900); await pg.locator('button[aria-label="Înapoi"]').first.click(); await pg.wait_for_timeout(900); await tap('button.tab:has-text("Planuri")', 900); await pg.screenshot(path='shots/e1.png')
        await tap('button.tab:has-text("Profil")', 900); await pg.screenshot(path='shots/e2.png')
        await tap('button.tab.plus', 1500); await pg.screenshot(path='shots/e3.png')
        await tap('button.tab:has-text("Acasă")', 900); await pg.mouse.wheel(0, 700); await pg.wait_for_timeout(500); await pg.screenshot(path='shots/e4.png')
        print(errs[:5])
        await b.close()
asyncio.run(main())
