// Local-only UI integration; every backend call is intercepted before the network.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import {createHash} from 'node:crypto';
import {chromium} from 'playwright';
const directory=path.resolve('website/dist'), policy=fs.readFileSync('website/descopera/.htaccess','utf8').match(/Content-Security-Policy "([^"]+)"/)[1];
let root=process.env.CEFACI_TEST_SITE_URL,server;
if(root&&!['127.0.0.1','localhost'].includes(new URL(root).hostname))throw Error('Only local test fixtures.');
if(!root){server=http.createServer((req,res)=>{let file=path.resolve(directory,'.'+new URL(req.url,'http://localhost').pathname);if(!file.startsWith(directory+path.sep)){res.writeHead(403).end();return;}if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file+='/index.html';if(!fs.existsSync(file)){res.writeHead(404).end();return;}res.writeHead(200,{'Content-Type':({'.html':'text/html','.css':'text/css','.js':'text/javascript','.webp':'image/webp','.woff2':'font/woff2','.png':'image/png'})[path.extname(file)],'Content-Security-Policy':policy});fs.createReadStream(file).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));root='http://127.0.0.1:'+server.address().port;}
const browser=await chromium.launch({headless:true}),errors=[],unexpected=[],calls=[],saved=new Map();let failOnce=false,offline=false;
try{
 fs.mkdirSync('release/quiz-ui',{recursive:true});
 for(const [i,width]of[320,390,768,1440].entries()){
 const ctx=await browser.newContext({viewport:{width,height:900},colorScheme:i===2?'dark':'light',reducedMotion:'reduce',extraHTTPHeaders:process.env.CEFACI_TEST_PROXY_HTTPS==='1'?{'X-Forwarded-Proto':'https'}:{}});
 await ctx.route('**/*',async route=>{const req=route.request(),u=new URL(req.url());if(u.origin===root)return route.continue();if(u.hostname!=='vqrmwuarjjntusfbqprx.supabase.co'){unexpected.push(u.origin);return route.abort();}const name=u.pathname.split('/').pop();if(!['launch_interest_submit','launch_interest_withdraw'].includes(name)){unexpected.push(name);return route.abort();}assert.equal(req.method(),'POST');assert(!req.headers().authorization);const p=req.postDataJSON();assert(createHash('sha256').update(p.p_receipt+':'+p.p_nonce).digest('hex').startsWith('000'));calls.push({name,p});if(offline)return route.abort();if(name==='launch_interest_submit'){if(saved.has(p.p_receipt))assert.deepEqual(saved.get(p.p_receipt),p);else saved.set(p.p_receipt,p);if(failOnce){failOnce=false;return route.abort();}return route.fulfill({json:{saved:true,email_requested:!!p.p_email}});}saved.delete(p.p_receipt);return route.fulfill({json:{withdrawn:true}});});
 const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));const startCalls=calls.length;
 const response=await page.goto(root+'/descopera/');assert(response.headers()['content-security-policy'].includes('/rest/v1/rpc/launch_interest_submit'));await page.evaluate(()=>document.fonts.ready);
 const check=async stage=>{assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,stage+' width '+width);await page.waitForFunction(()=>{const img=document.getElementById('quiz-screen');return img.complete&&img.naturalWidth>0;});await page.screenshot({path:`release/quiz-ui/${width}-${stage}.png`,fullPage:true});};
 await check('start');assert(await page.locator('#quiz-next').isDisabled());
 const choice=page.locator('.quiz-choice').nth(i%3);await choice.focus();await page.keyboard.press('Enter');assert.equal(await choice.getAttribute('aria-pressed'),'true');await page.locator('#quiz-next').click();await page.locator('.quiz-choice').nth(i%3).click();await page.locator('#quiz-back').click();assert.equal(await page.locator('.quiz-choice').nth(i%3).getAttribute('aria-pressed'),'true');await page.locator('#quiz-next').click();assert.equal(await page.locator('.quiz-choice').nth(i%3).getAttribute('aria-pressed'),'true');await page.locator('#quiz-next').click();await check('plan');await page.locator('#quiz-next').click();await page.getByRole('heading',{name:'Ai folosi CeFaci la lansare?'}).waitFor();await check('vote');assert.equal(calls.length,startCalls,'No backend request before explicit submit');
 await page.locator('.quiz-choice').nth(i%3).click();await page.locator('#quiz-next').click();await check('form');assert.equal(await page.locator('input[name=notify]').isChecked(),false);await page.locator('input[name=name]').fill('Test '+width);await page.locator('input[name=feedback]').check();
 if(i%2===0){await page.locator('input[name=email]').fill('test'+width+'@example.invalid');await page.getByRole('button',{name:'Trimite părerea mea'}).click();assert.equal(calls.length,startCalls);await page.getByRole('status').filter({hasText:'Bifează acordul'}).waitFor();await page.locator('input[name=notify]').check();}
 failOnce=i===0;await page.getByRole('button',{name:'Trimite părerea mea'}).click();
 if(i===0){await page.getByRole('button',{name:'Reîncearcă trimiterea'}).waitFor();assert(await page.locator('input[name=name]').isDisabled());await page.getByRole('button',{name:'Reîncearcă trimiterea'}).click();}
 await page.getByRole('heading',{name:'Mulțumim. Pe bune. Ne ajută mult.'}).waitFor({timeout:30000});assert.equal(saved.size,1);await check('saved');assert.equal((await ctx.cookies()).length,0);assert.deepEqual(await page.evaluate(()=>Object.keys(localStorage)),[]);assert.deepEqual(await page.evaluate(()=>Object.keys(sessionStorage)),[]);
 const privateLink=await page.getByRole('textbox',{name:'Link privat pentru retragere'}).inputValue();const receipt=new URL(privateLink).hash;await page.goto(root+'/descopera/'+receipt);await page.getByRole('button',{name:'Confirm retragerea răspunsului'}).waitFor();assert.equal(saved.size,1,'Opening the private link must not withdraw');assert.equal(new URL(page.url()).hash,'','Private fragment cleared from URL');offline=i===0;await page.getByRole('button',{name:'Confirm retragerea răspunsului'}).click();if(offline){await page.getByRole('status').filter({hasText:'Conexiunea s-a întrerupt'}).waitFor();offline=false;await page.getByRole('button',{name:'Confirm retragerea răspunsului'}).click();}await page.getByText('Retragerea a fost procesată.',{exact:false}).waitFor();assert.equal(saved.size,0);await ctx.close();
 }
 assert.deepEqual(errors,[]);assert.deepEqual(unexpected,[]);
 console.log('PASS: quiz 4 widths/light+dark, every answer, keyboard/back, screenshots, no pre-submit requests or storage, optional email/separate consent, lost-response idempotent retry, private withdrawal with network recovery; real CSP enforced.');
}finally{await browser.close();if(server)await new Promise(r=>server.close(r));}
